#! /bin/bash
### Set name.
#$ -N lmcut
### Set shell.
#$ -S /bin/bash
### Execute job from current working directory.
#$ -cwd
### Export all environment variables to the job context.
#$ -V
### Redirect stdout and stderr.
#$ -e driver.err
#$ -o driver.log
### Set queue.
#$ -q "all.q@ase*"
### Number of tasks.
#$ -t 1-2
### Priority ([-1023,1024], default: 0).
#$ -p -10
### Restrict to certain machines.
## (not used)
### Send mail? -m can be e.g. (b)eginning, (e)nd, (n)ever.
#$ -m n
### Extra options.
## (not used)


declare -a RUN_IDS=(2 1)
NUM_TASKS=2

function format {
    printf "%05d" $1
}

function get_run_id {
    if (( $1 < 1 || $1 > $NUM_TASKS )); then
        echo "error: SGE_TASK_ID must be in range 1..$NUM_TASKS but is '$1'" 1>&2
        exit 2
    fi
    if (( ${#RUN_IDS[@]} == $NUM_TASKS )); then
        echo ${RUN_IDS[$(($1-1))]}
    else
        echo $1
    fi
}

RUN=$(get_run_id $SGE_TASK_ID)
let "LOWER = ((RUN - 1) / 100) * 100 + 1"
let "UPPER = (((RUN + 99) / 100) * 100)"
DIR="runs-$(format $LOWER)-$(format $UPPER)/$(format $RUN)"

./$DIR/run
RETCODE=$?
if (( $RETCODE != 0 )); then
    echo Run $RUN returned $RETCODE >> driver.err
fi
