(define (problem transport-city-sequential-63nodes-1000size-4degree-100mindistance-4trucks-30packages-2014seed)
(:domain transport)
(:objects
pnum1 pnum2 pnum3 pnum0  - pnum
package-bag1 package-bag2 package-bag3 package-bag4 package-bag5 package-bag6 package-bag7 package-bag8 package-bag9 package-bag10 package-bag11 package-bag12 package-bag13 package-bag14 package-bag15 package-bag16 package-bag17 package-bag18 package-bag19 package-bag20 package-bag21 package-bag22  - package
capacity-0 capacity-1 capacity-2 capacity-3 capacity-4  - capacity-number
city-loc-1 city-loc-2 city-loc-3 city-loc-4 city-loc-5 city-loc-6 city-loc-7 city-loc-8 city-loc-9 city-loc-10 city-loc-11 city-loc-12 city-loc-13 city-loc-14 city-loc-15 city-loc-16 city-loc-17 city-loc-18 city-loc-19 city-loc-20 city-loc-21 city-loc-22 city-loc-23 city-loc-24 city-loc-25 city-loc-26 city-loc-27 city-loc-28 city-loc-29 city-loc-30 city-loc-31 city-loc-32 city-loc-33 city-loc-34 city-loc-35 city-loc-36 city-loc-37 city-loc-38 city-loc-39 city-loc-40 city-loc-41 city-loc-42 city-loc-43 city-loc-44 city-loc-45 city-loc-46 city-loc-47 city-loc-48 city-loc-49 city-loc-50 city-loc-51 city-loc-52 city-loc-53 city-loc-54 city-loc-55 city-loc-56 city-loc-57 city-loc-58 city-loc-59 city-loc-60 city-loc-61 city-loc-62 city-loc-63  - location
truck-1 truck-2 truck-3 truck-4  - vehicle
)
(:init (road city-loc-49 city-loc-32)
(road city-loc-15 city-loc-38)
(road city-loc-39 city-loc-40)
(road city-loc-35 city-loc-47)
(road city-loc-60 city-loc-48)
(road city-loc-14 city-loc-12)
(at-vehicle truck-1 city-loc-36)
(road city-loc-42 city-loc-58)
(road city-loc-9 city-loc-24)
(road city-loc-52 city-loc-53)
(road city-loc-1 city-loc-24)
(road city-loc-32 city-loc-10)
(road city-loc-11 city-loc-61)
(road city-loc-47 city-loc-3)
(road city-loc-13 city-loc-9)
(capacity truck-3 capacity-3)
(road city-loc-37 city-loc-52)
(road city-loc-29 city-loc-61)
(capacity-predecessor capacity-0 capacity-1)
(road city-loc-34 city-loc-14)
(road city-loc-38 city-loc-5)
(road city-loc-2 city-loc-23)
(road city-loc-17 city-loc-10)
(road city-loc-43 city-loc-34)
(road city-loc-14 city-loc-57)
(road city-loc-1 city-loc-42)
(road city-loc-53 city-loc-37)
(road city-loc-59 city-loc-36)
(road city-loc-39 city-loc-25)
(road city-loc-62 city-loc-18)
(capacity truck-1 capacity-4)
(road city-loc-22 city-loc-7)
(road city-loc-53 city-loc-52)
(road city-loc-56 city-loc-43)
(road city-loc-13 city-loc-28)
(road city-loc-15 city-loc-18)
(road city-loc-63 city-loc-24)
(road city-loc-30 city-loc-44)
(road city-loc-3 city-loc-39)
(road city-loc-49 city-loc-10)
(road city-loc-29 city-loc-37)
(road city-loc-24 city-loc-63)
(road city-loc-32 city-loc-49)
(road city-loc-41 city-loc-15)
(road city-loc-25 city-loc-60)
(road city-loc-61 city-loc-12)
(road city-loc-27 city-loc-19)
(road city-loc-5 city-loc-38)
(road city-loc-12 city-loc-29)
(road city-loc-14 city-loc-34)
(road city-loc-58 city-loc-7)
(capacity truck-2 capacity-4)
(road city-loc-61 city-loc-37)
(road city-loc-18 city-loc-41)
(road city-loc-50 city-loc-21)
(road city-loc-31 city-loc-54)
(road city-loc-19 city-loc-2)
(road city-loc-43 city-loc-29)
(road city-loc-36 city-loc-16)
(road city-loc-5 city-loc-41)
(road city-loc-23 city-loc-2)
(road city-loc-55 city-loc-10)
(road city-loc-49 city-loc-14)
(road city-loc-33 city-loc-46)
(road city-loc-8 city-loc-9)
(road city-loc-54 city-loc-48)
(road city-loc-14 city-loc-49)
(road city-loc-36 city-loc-43)
(road city-loc-18 city-loc-62)
(road city-loc-63 city-loc-1)
(road city-loc-57 city-loc-47)
(road city-loc-31 city-loc-46)
(road city-loc-54 city-loc-11)
(road city-loc-11 city-loc-52)
(road city-loc-10 city-loc-17)
(road city-loc-34 city-loc-43)
(road city-loc-9 city-loc-8)
(road city-loc-37 city-loc-61)
(road city-loc-20 city-loc-62)
(road city-loc-61 city-loc-11)
(road city-loc-18 city-loc-40)
(road city-loc-58 city-loc-30)
(road city-loc-9 city-loc-1)
(road city-loc-39 city-loc-3)
(road city-loc-29 city-loc-34)
(road city-loc-56 city-loc-36)
(road city-loc-54 city-loc-57)
(road city-loc-20 city-loc-18)
(road city-loc-3 city-loc-26)
(road city-loc-9 city-loc-42)
(road city-loc-5 city-loc-45)
(road city-loc-9 city-loc-58)
(road city-loc-54 city-loc-31)
(road city-loc-24 city-loc-50)
(road city-loc-48 city-loc-60)
(road city-loc-54 city-loc-12)
(road city-loc-6 city-loc-56)
(road city-loc-9 city-loc-13)
(road city-loc-53 city-loc-27)
(road city-loc-19 city-loc-46)
(road city-loc-21 city-loc-5)
(road city-loc-7 city-loc-32)
(road city-loc-46 city-loc-33)
(road city-loc-13 city-loc-58)
(road city-loc-54 city-loc-61)
(road city-loc-59 city-loc-16)
(road city-loc-23 city-loc-19)
(road city-loc-1 city-loc-9)
(road city-loc-32 city-loc-44)
(road city-loc-60 city-loc-25)
(road city-loc-26 city-loc-39)
(road city-loc-42 city-loc-7)
(road city-loc-47 city-loc-57)
(road city-loc-52 city-loc-27)
(road city-loc-46 city-loc-31)
(road city-loc-19 city-loc-23)
(road city-loc-26 city-loc-41)
(road city-loc-45 city-loc-5)
(road city-loc-45 city-loc-50)
(road city-loc-7 city-loc-42)
(road city-loc-30 city-loc-58)
(capacity-predecessor capacity-1 capacity-2)
(road city-loc-17 city-loc-43)
(road city-loc-63 city-loc-21)
(road city-loc-13 city-loc-51)
(road city-loc-45 city-loc-38)
(road city-loc-15 city-loc-20)
(road city-loc-40 city-loc-39)
(road city-loc-29 city-loc-43)
(road city-loc-22 city-loc-14)
(road city-loc-26 city-loc-3)
(road city-loc-18 city-loc-15)
(road city-loc-28 city-loc-13)
(road city-loc-52 city-loc-11)
(road city-loc-48 city-loc-54)
(road city-loc-5 city-loc-15)
(road city-loc-25 city-loc-40)
(road city-loc-34 city-loc-49)
(road city-loc-55 city-loc-16)
(road city-loc-50 city-loc-63)
(road city-loc-51 city-loc-28)
(road city-loc-16 city-loc-17)
(road city-loc-12 city-loc-14)
(road city-loc-3 city-loc-47)
(road city-loc-31 city-loc-11)
(road city-loc-63 city-loc-50)
(road city-loc-19 city-loc-27)
(road city-loc-38 city-loc-15)
(road city-loc-4 city-loc-24)
(road city-loc-27 city-loc-52)
(road city-loc-17 city-loc-36)
(road city-loc-10 city-loc-32)
(road city-loc-51 city-loc-13)
(road city-loc-58 city-loc-42)
(road city-loc-48 city-loc-31)
(road city-loc-31 city-loc-60)
(at-vehicle truck-3 city-loc-8)
(road city-loc-6 city-loc-29)
(road city-loc-17 city-loc-49)
(road city-loc-35 city-loc-57)
(road city-loc-12 city-loc-54)
(capacity truck-4 capacity-4)
(road city-loc-57 city-loc-14)
(road city-loc-3 city-loc-48)
(road city-loc-48 city-loc-3)
(road city-loc-33 city-loc-60)
(road city-loc-61 city-loc-52)
(road city-loc-42 city-loc-1)
(road city-loc-8 city-loc-24)
(road city-loc-43 city-loc-17)
(road city-loc-46 city-loc-60)
(road city-loc-48 city-loc-35)
(road city-loc-56 city-loc-6)
(road city-loc-40 city-loc-25)
(road city-loc-61 city-loc-54)
(road city-loc-24 city-loc-8)
(road city-loc-11 city-loc-31)
(road city-loc-18 city-loc-20)
(road city-loc-17 city-loc-16)
(road city-loc-34 city-loc-29)
(road city-loc-37 city-loc-53)
(road city-loc-35 city-loc-54)
(road city-loc-24 city-loc-1)
(road city-loc-1 city-loc-22)
(road city-loc-52 city-loc-37)
(road city-loc-57 city-loc-54)
(road city-loc-29 city-loc-12)
(road city-loc-3 city-loc-35)
(road city-loc-41 city-loc-18)
(road city-loc-42 city-loc-9)
(road city-loc-36 city-loc-17)
(road city-loc-49 city-loc-17)
(road city-loc-40 city-loc-18)
(road city-loc-22 city-loc-1)
(road city-loc-10 city-loc-49)
(road city-loc-25 city-loc-39)
(road city-loc-22 city-loc-57)
(at-vehicle truck-4 city-loc-22)
(road city-loc-21 city-loc-50)
(road city-loc-36 city-loc-56)
(road city-loc-52 city-loc-61)
(road city-loc-15 city-loc-5)
(road city-loc-39 city-loc-26)
(road city-loc-42 city-loc-22)
(road city-loc-2 city-loc-19)
(road city-loc-37 city-loc-29)
(road city-loc-21 city-loc-26)
(road city-loc-24 city-loc-9)
(at-vehicle truck-2 city-loc-40)
(road city-loc-15 city-loc-41)
(road city-loc-60 city-loc-46)
(road city-loc-7 city-loc-58)
(road city-loc-62 city-loc-20)
(road city-loc-35 city-loc-3)
(road city-loc-1 city-loc-63)
(road city-loc-24 city-loc-4)
(road city-loc-57 city-loc-12)
(road city-loc-16 city-loc-36)
(road city-loc-29 city-loc-6)
(road city-loc-26 city-loc-21)
(road city-loc-12 city-loc-61)
(road city-loc-47 city-loc-35)
(road city-loc-7 city-loc-22)
(road city-loc-49 city-loc-34)
(road city-loc-41 city-loc-5)
(road city-loc-20 city-loc-15)
(capacity-predecessor capacity-2 capacity-3)
(road city-loc-44 city-loc-30)
(capacity-predecessor capacity-3 capacity-4)
(road city-loc-34 city-loc-17)
(road city-loc-27 city-loc-53)
(road city-loc-58 city-loc-13)
(road city-loc-38 city-loc-45)
(road city-loc-60 city-loc-33)
(road city-loc-58 city-loc-9)
(road city-loc-17 city-loc-34)
(road city-loc-54 city-loc-35)
(road city-loc-11 city-loc-54)
(road city-loc-37 city-loc-6)
(road city-loc-50 city-loc-24)
(road city-loc-57 city-loc-22)
(road city-loc-61 city-loc-29)
(road city-loc-43 city-loc-36)
(road city-loc-21 city-loc-63)
(road city-loc-22 city-loc-42)
(road city-loc-6 city-loc-37)
(road city-loc-16 city-loc-55)
(road city-loc-31 city-loc-48)
(road city-loc-50 city-loc-45)
(road city-loc-60 city-loc-31)
(road city-loc-57 city-loc-35)
(road city-loc-14 city-loc-22)
(road city-loc-41 city-loc-26)
(road city-loc-4 city-loc-50)
(road city-loc-12 city-loc-57)
(road city-loc-28 city-loc-51)
(road city-loc-16 city-loc-59)
(road city-loc-44 city-loc-32)
(road city-loc-36 city-loc-59)
(road city-loc-50 city-loc-4)
(road city-loc-46 city-loc-19)
(road city-loc-10 city-loc-55)
(road city-loc-5 city-loc-21)
(road city-loc-32 city-loc-7)
(road city-loc-35 city-loc-48)
(road city-loc-43 city-loc-56)
(package-less pnum1 pnum2)
(package-less pnum2 pnum3)
(= (total-cost ) 0)
(= (road-length city-loc-9 city-loc-1) 17)
(= (road-length city-loc-1 city-loc-9) 17)
(= (road-length city-loc-9 city-loc-8) 14)
(= (road-length city-loc-8 city-loc-9) 14)
(= (road-length city-loc-13 city-loc-9) 16)
(= (road-length city-loc-9 city-loc-13) 16)
(= (road-length city-loc-14 city-loc-12) 16)
(= (road-length city-loc-12 city-loc-14) 16)
(= (road-length city-loc-15 city-loc-5) 16)
(= (road-length city-loc-5 city-loc-15) 16)
(= (road-length city-loc-17 city-loc-10) 17)
(= (road-length city-loc-10 city-loc-17) 17)
(= (road-length city-loc-17 city-loc-16) 15)
(= (road-length city-loc-16 city-loc-17) 15)
(= (road-length city-loc-18 city-loc-15) 12)
(= (road-length city-loc-15 city-loc-18) 12)
(= (road-length city-loc-19 city-loc-2) 14)
(= (road-length city-loc-2 city-loc-19) 14)
(= (road-length city-loc-20 city-loc-15) 11)
(= (road-length city-loc-15 city-loc-20) 11)
(= (road-length city-loc-20 city-loc-18) 14)
(= (road-length city-loc-18 city-loc-20) 14)
(= (road-length city-loc-21 city-loc-5) 16)
(= (road-length city-loc-5 city-loc-21) 16)
(= (road-length city-loc-22 city-loc-1) 16)
(= (road-length city-loc-1 city-loc-22) 16)
(= (road-length city-loc-22 city-loc-7) 13)
(= (road-length city-loc-7 city-loc-22) 13)
(= (road-length city-loc-22 city-loc-14) 17)
(= (road-length city-loc-14 city-loc-22) 17)
(= (road-length city-loc-23 city-loc-2) 12)
(= (road-length city-loc-2 city-loc-23) 12)
(= (road-length city-loc-23 city-loc-19) 16)
(= (road-length city-loc-19 city-loc-23) 16)
(= (road-length city-loc-24 city-loc-1) 17)
(= (road-length city-loc-1 city-loc-24) 17)
(= (road-length city-loc-24 city-loc-4) 14)
(= (road-length city-loc-4 city-loc-24) 14)
(= (road-length city-loc-24 city-loc-8) 13)
(= (road-length city-loc-8 city-loc-24) 13)
(= (road-length city-loc-24 city-loc-9) 13)
(= (road-length city-loc-9 city-loc-24) 13)
(= (road-length city-loc-26 city-loc-3) 13)
(= (road-length city-loc-3 city-loc-26) 13)
(= (road-length city-loc-26 city-loc-21) 17)
(= (road-length city-loc-21 city-loc-26) 17)
(= (road-length city-loc-27 city-loc-19) 15)
(= (road-length city-loc-19 city-loc-27) 15)
(= (road-length city-loc-28 city-loc-13) 13)
(= (road-length city-loc-13 city-loc-28) 13)
(= (road-length city-loc-29 city-loc-6) 14)
(= (road-length city-loc-6 city-loc-29) 14)
(= (road-length city-loc-29 city-loc-12) 16)
(= (road-length city-loc-12 city-loc-29) 16)
(= (road-length city-loc-31 city-loc-11) 13)
(= (road-length city-loc-11 city-loc-31) 13)
(= (road-length city-loc-32 city-loc-7) 16)
(= (road-length city-loc-7 city-loc-32) 16)
(= (road-length city-loc-32 city-loc-10) 14)
(= (road-length city-loc-10 city-loc-32) 14)
(= (road-length city-loc-34 city-loc-14) 11)
(= (road-length city-loc-14 city-loc-34) 11)
(= (road-length city-loc-34 city-loc-17) 13)
(= (road-length city-loc-17 city-loc-34) 13)
(= (road-length city-loc-34 city-loc-29) 17)
(= (road-length city-loc-29 city-loc-34) 17)
(= (road-length city-loc-35 city-loc-3) 16)
(= (road-length city-loc-3 city-loc-35) 16)
(= (road-length city-loc-36 city-loc-16) 16)
(= (road-length city-loc-16 city-loc-36) 16)
(= (road-length city-loc-36 city-loc-17) 17)
(= (road-length city-loc-17 city-loc-36) 17)
(= (road-length city-loc-37 city-loc-6) 12)
(= (road-length city-loc-6 city-loc-37) 12)
(= (road-length city-loc-37 city-loc-29) 15)
(= (road-length city-loc-29 city-loc-37) 15)
(= (road-length city-loc-38 city-loc-5) 11)
(= (road-length city-loc-5 city-loc-38) 11)
(= (road-length city-loc-38 city-loc-15) 13)
(= (road-length city-loc-15 city-loc-38) 13)
(= (road-length city-loc-39 city-loc-3) 11)
(= (road-length city-loc-3 city-loc-39) 11)
(= (road-length city-loc-39 city-loc-25) 16)
(= (road-length city-loc-25 city-loc-39) 16)
(= (road-length city-loc-39 city-loc-26) 11)
(= (road-length city-loc-26 city-loc-39) 11)
(= (road-length city-loc-40 city-loc-18) 16)
(= (road-length city-loc-18 city-loc-40) 16)
(= (road-length city-loc-40 city-loc-25) 16)
(= (road-length city-loc-25 city-loc-40) 16)
(= (road-length city-loc-40 city-loc-39) 17)
(= (road-length city-loc-39 city-loc-40) 17)
(= (road-length city-loc-41 city-loc-5) 11)
(= (road-length city-loc-5 city-loc-41) 11)
(= (road-length city-loc-41 city-loc-15) 14)
(= (road-length city-loc-15 city-loc-41) 14)
(= (road-length city-loc-41 city-loc-18) 12)
(= (road-length city-loc-18 city-loc-41) 12)
(= (road-length city-loc-41 city-loc-26) 13)
(= (road-length city-loc-26 city-loc-41) 13)
(= (road-length city-loc-42 city-loc-1) 11)
(= (road-length city-loc-1 city-loc-42) 11)
(= (road-length city-loc-42 city-loc-7) 15)
(= (road-length city-loc-7 city-loc-42) 15)
(= (road-length city-loc-42 city-loc-9) 12)
(= (road-length city-loc-9 city-loc-42) 12)
(= (road-length city-loc-42 city-loc-22) 17)
(= (road-length city-loc-22 city-loc-42) 17)
(= (road-length city-loc-43 city-loc-17) 13)
(= (road-length city-loc-17 city-loc-43) 13)
(= (road-length city-loc-43 city-loc-29) 14)
(= (road-length city-loc-29 city-loc-43) 14)
(= (road-length city-loc-43 city-loc-34) 14)
(= (road-length city-loc-34 city-loc-43) 14)
(= (road-length city-loc-43 city-loc-36) 14)
(= (road-length city-loc-36 city-loc-43) 14)
(= (road-length city-loc-44 city-loc-30) 11)
(= (road-length city-loc-30 city-loc-44) 11)
(= (road-length city-loc-44 city-loc-32) 11)
(= (road-length city-loc-32 city-loc-44) 11)
(= (road-length city-loc-45 city-loc-5) 13)
(= (road-length city-loc-5 city-loc-45) 13)
(= (road-length city-loc-45 city-loc-38) 11)
(= (road-length city-loc-38 city-loc-45) 11)
(= (road-length city-loc-46 city-loc-19) 16)
(= (road-length city-loc-19 city-loc-46) 16)
(= (road-length city-loc-46 city-loc-31) 11)
(= (road-length city-loc-31 city-loc-46) 11)
(= (road-length city-loc-46 city-loc-33) 11)
(= (road-length city-loc-33 city-loc-46) 11)
(= (road-length city-loc-47 city-loc-3) 12)
(= (road-length city-loc-3 city-loc-47) 12)
(= (road-length city-loc-47 city-loc-35) 11)
(= (road-length city-loc-35 city-loc-47) 11)
(= (road-length city-loc-48 city-loc-3) 13)
(= (road-length city-loc-3 city-loc-48) 13)
(= (road-length city-loc-48 city-loc-31) 11)
(= (road-length city-loc-31 city-loc-48) 11)
(= (road-length city-loc-48 city-loc-35) 13)
(= (road-length city-loc-35 city-loc-48) 13)
(= (road-length city-loc-49 city-loc-10) 16)
(= (road-length city-loc-10 city-loc-49) 16)
(= (road-length city-loc-49 city-loc-14) 11)
(= (road-length city-loc-14 city-loc-49) 11)
(= (road-length city-loc-49 city-loc-17) 15)
(= (road-length city-loc-17 city-loc-49) 15)
(= (road-length city-loc-49 city-loc-32) 14)
(= (road-length city-loc-32 city-loc-49) 14)
(= (road-length city-loc-49 city-loc-34) 11)
(= (road-length city-loc-34 city-loc-49) 11)
(= (road-length city-loc-50 city-loc-4) 14)
(= (road-length city-loc-4 city-loc-50) 14)
(= (road-length city-loc-50 city-loc-21) 13)
(= (road-length city-loc-21 city-loc-50) 13)
(= (road-length city-loc-50 city-loc-24) 15)
(= (road-length city-loc-24 city-loc-50) 15)
(= (road-length city-loc-50 city-loc-45) 13)
(= (road-length city-loc-45 city-loc-50) 13)
(= (road-length city-loc-51 city-loc-13) 11)
(= (road-length city-loc-13 city-loc-51) 11)
(= (road-length city-loc-51 city-loc-28) 13)
(= (road-length city-loc-28 city-loc-51) 13)
(= (road-length city-loc-52 city-loc-11) 14)
(= (road-length city-loc-11 city-loc-52) 14)
(= (road-length city-loc-52 city-loc-27) 15)
(= (road-length city-loc-27 city-loc-52) 15)
(= (road-length city-loc-52 city-loc-37) 10)
(= (road-length city-loc-37 city-loc-52) 10)
(= (road-length city-loc-53 city-loc-27) 11)
(= (road-length city-loc-27 city-loc-53) 11)
(= (road-length city-loc-53 city-loc-37) 14)
(= (road-length city-loc-37 city-loc-53) 14)
(= (road-length city-loc-53 city-loc-52) 11)
(= (road-length city-loc-52 city-loc-53) 11)
(= (road-length city-loc-54 city-loc-11) 13)
(= (road-length city-loc-11 city-loc-54) 13)
(= (road-length city-loc-54 city-loc-12) 14)
(= (road-length city-loc-12 city-loc-54) 14)
(= (road-length city-loc-54 city-loc-31) 13)
(= (road-length city-loc-31 city-loc-54) 13)
(= (road-length city-loc-54 city-loc-35) 11)
(= (road-length city-loc-35 city-loc-54) 11)
(= (road-length city-loc-54 city-loc-48) 13)
(= (road-length city-loc-48 city-loc-54) 13)
(= (road-length city-loc-55 city-loc-10) 13)
(= (road-length city-loc-10 city-loc-55) 13)
(= (road-length city-loc-55 city-loc-16) 11)
(= (road-length city-loc-16 city-loc-55) 11)
(= (road-length city-loc-56 city-loc-6) 12)
(= (road-length city-loc-6 city-loc-56) 12)
(= (road-length city-loc-56 city-loc-36) 13)
(= (road-length city-loc-36 city-loc-56) 13)
(= (road-length city-loc-56 city-loc-43) 13)
(= (road-length city-loc-43 city-loc-56) 13)
(= (road-length city-loc-57 city-loc-12) 14)
(= (road-length city-loc-12 city-loc-57) 14)
(= (road-length city-loc-57 city-loc-14) 16)
(= (road-length city-loc-14 city-loc-57) 16)
(= (road-length city-loc-57 city-loc-22) 12)
(= (road-length city-loc-22 city-loc-57) 12)
(= (road-length city-loc-57 city-loc-35) 12)
(= (road-length city-loc-35 city-loc-57) 12)
(= (road-length city-loc-57 city-loc-47) 17)
(= (road-length city-loc-47 city-loc-57) 17)
(= (road-length city-loc-57 city-loc-54) 16)
(= (road-length city-loc-54 city-loc-57) 16)
(= (road-length city-loc-58 city-loc-7) 16)
(= (road-length city-loc-7 city-loc-58) 16)
(= (road-length city-loc-58 city-loc-9) 14)
(= (road-length city-loc-9 city-loc-58) 14)
(= (road-length city-loc-58 city-loc-13) 16)
(= (road-length city-loc-13 city-loc-58) 16)
(= (road-length city-loc-58 city-loc-30) 12)
(= (road-length city-loc-30 city-loc-58) 12)
(= (road-length city-loc-58 city-loc-42) 13)
(= (road-length city-loc-42 city-loc-58) 13)
(= (road-length city-loc-59 city-loc-16) 12)
(= (road-length city-loc-16 city-loc-59) 12)
(= (road-length city-loc-59 city-loc-36) 13)
(= (road-length city-loc-36 city-loc-59) 13)
(= (road-length city-loc-60 city-loc-25) 12)
(= (road-length city-loc-25 city-loc-60) 12)
(= (road-length city-loc-60 city-loc-31) 15)
(= (road-length city-loc-31 city-loc-60) 15)
(= (road-length city-loc-60 city-loc-33) 12)
(= (road-length city-loc-33 city-loc-60) 12)
(= (road-length city-loc-60 city-loc-46) 12)
(= (road-length city-loc-46 city-loc-60) 12)
(= (road-length city-loc-60 city-loc-48) 15)
(= (road-length city-loc-48 city-loc-60) 15)
(= (road-length city-loc-61 city-loc-11) 11)
(= (road-length city-loc-11 city-loc-61) 11)
(= (road-length city-loc-61 city-loc-12) 11)
(= (road-length city-loc-12 city-loc-61) 11)
(= (road-length city-loc-61 city-loc-29) 14)
(= (road-length city-loc-29 city-loc-61) 14)
(= (road-length city-loc-61 city-loc-37) 16)
(= (road-length city-loc-37 city-loc-61) 16)
(= (road-length city-loc-61 city-loc-52) 16)
(= (road-length city-loc-52 city-loc-61) 16)
(= (road-length city-loc-61 city-loc-54) 15)
(= (road-length city-loc-54 city-loc-61) 15)
(= (road-length city-loc-62 city-loc-18) 12)
(= (road-length city-loc-18 city-loc-62) 12)
(= (road-length city-loc-62 city-loc-20) 12)
(= (road-length city-loc-20 city-loc-62) 12)
(= (road-length city-loc-63 city-loc-1) 11)
(= (road-length city-loc-1 city-loc-63) 11)
(= (road-length city-loc-63 city-loc-21) 11)
(= (road-length city-loc-21 city-loc-63) 11)
(= (road-length city-loc-63 city-loc-24) 12)
(= (road-length city-loc-24 city-loc-63) 12)
(= (road-length city-loc-63 city-loc-50) 13)
(= (road-length city-loc-50 city-loc-63) 13)
(count-package package-bag1 city-loc-12 pnum3)
(count-package package-bag2 city-loc-35 pnum1)
(count-package package-bag2 city-loc-3 pnum1)
(count-package package-bag3 city-loc-55 pnum1)
(count-package package-bag3 city-loc-59 pnum1)
(count-package package-bag4 city-loc-22 pnum1)
(count-package package-bag4 city-loc-47 pnum1)
(count-package package-bag5 city-loc-16 pnum1)
(count-package package-bag5 city-loc-9 pnum1)
(count-package package-bag6 city-loc-20 pnum1)
(count-package package-bag6 city-loc-48 pnum1)
(count-package package-bag7 city-loc-19 pnum2)
(count-package package-bag8 city-loc-35 pnum1)
(count-package package-bag9 city-loc-4 pnum1)
(count-package package-bag10 city-loc-5 pnum1)
(count-package package-bag11 city-loc-58 pnum1)
(count-package package-bag12 city-loc-33 pnum1)
(count-package package-bag13 city-loc-13 pnum1)
(count-package package-bag14 city-loc-62 pnum1)
(count-package package-bag15 city-loc-22 pnum1)
(count-package package-bag16 city-loc-41 pnum1)
(count-package package-bag17 city-loc-52 pnum1)
(count-package package-bag18 city-loc-37 pnum1)
(count-package package-bag19 city-loc-60 pnum1)
(count-package package-bag20 city-loc-44 pnum1)
(count-package package-bag21 city-loc-6 pnum1)
(count-package package-bag22 city-loc-18 pnum1)
(package-less pnum0 pnum1)
(count-package package-bag1 truck-1 pnum0)
(count-package package-bag1 truck-2 pnum0)
(count-package package-bag1 truck-3 pnum0)
(count-package package-bag1 truck-4 pnum0)
(count-package package-bag1 city-loc-1 pnum0)
(count-package package-bag1 city-loc-2 pnum0)
(count-package package-bag1 city-loc-3 pnum0)
(count-package package-bag1 city-loc-4 pnum0)
(count-package package-bag1 city-loc-5 pnum0)
(count-package package-bag1 city-loc-6 pnum0)
(count-package package-bag1 city-loc-7 pnum0)
(count-package package-bag1 city-loc-8 pnum0)
(count-package package-bag1 city-loc-9 pnum0)
(count-package package-bag1 city-loc-10 pnum0)
(count-package package-bag1 city-loc-11 pnum0)
(count-package package-bag1 city-loc-13 pnum0)
(count-package package-bag1 city-loc-14 pnum0)
(count-package package-bag1 city-loc-15 pnum0)
(count-package package-bag1 city-loc-16 pnum0)
(count-package package-bag1 city-loc-17 pnum0)
(count-package package-bag1 city-loc-18 pnum0)
(count-package package-bag1 city-loc-19 pnum0)
(count-package package-bag1 city-loc-20 pnum0)
(count-package package-bag1 city-loc-21 pnum0)
(count-package package-bag1 city-loc-22 pnum0)
(count-package package-bag1 city-loc-23 pnum0)
(count-package package-bag1 city-loc-24 pnum0)
(count-package package-bag1 city-loc-25 pnum0)
(count-package package-bag1 city-loc-26 pnum0)
(count-package package-bag1 city-loc-27 pnum0)
(count-package package-bag1 city-loc-28 pnum0)
(count-package package-bag1 city-loc-29 pnum0)
(count-package package-bag1 city-loc-30 pnum0)
(count-package package-bag1 city-loc-31 pnum0)
(count-package package-bag1 city-loc-32 pnum0)
(count-package package-bag1 city-loc-33 pnum0)
(count-package package-bag1 city-loc-34 pnum0)
(count-package package-bag1 city-loc-35 pnum0)
(count-package package-bag1 city-loc-36 pnum0)
(count-package package-bag1 city-loc-37 pnum0)
(count-package package-bag1 city-loc-38 pnum0)
(count-package package-bag1 city-loc-39 pnum0)
(count-package package-bag1 city-loc-40 pnum0)
(count-package package-bag1 city-loc-41 pnum0)
(count-package package-bag1 city-loc-42 pnum0)
(count-package package-bag1 city-loc-43 pnum0)
(count-package package-bag1 city-loc-44 pnum0)
(count-package package-bag1 city-loc-45 pnum0)
(count-package package-bag1 city-loc-46 pnum0)
(count-package package-bag1 city-loc-47 pnum0)
(count-package package-bag1 city-loc-48 pnum0)
(count-package package-bag1 city-loc-49 pnum0)
(count-package package-bag1 city-loc-50 pnum0)
(count-package package-bag1 city-loc-51 pnum0)
(count-package package-bag1 city-loc-52 pnum0)
(count-package package-bag1 city-loc-53 pnum0)
(count-package package-bag1 city-loc-54 pnum0)
(count-package package-bag1 city-loc-55 pnum0)
(count-package package-bag1 city-loc-56 pnum0)
(count-package package-bag1 city-loc-57 pnum0)
(count-package package-bag1 city-loc-58 pnum0)
(count-package package-bag1 city-loc-59 pnum0)
(count-package package-bag1 city-loc-60 pnum0)
(count-package package-bag1 city-loc-61 pnum0)
(count-package package-bag1 city-loc-62 pnum0)
(count-package package-bag1 city-loc-63 pnum0)
(count-package package-bag2 truck-1 pnum0)
(count-package package-bag2 truck-2 pnum0)
(count-package package-bag2 truck-3 pnum0)
(count-package package-bag2 truck-4 pnum0)
(count-package package-bag2 city-loc-1 pnum0)
(count-package package-bag2 city-loc-2 pnum0)
(count-package package-bag2 city-loc-4 pnum0)
(count-package package-bag2 city-loc-5 pnum0)
(count-package package-bag2 city-loc-6 pnum0)
(count-package package-bag2 city-loc-7 pnum0)
(count-package package-bag2 city-loc-8 pnum0)
(count-package package-bag2 city-loc-9 pnum0)
(count-package package-bag2 city-loc-10 pnum0)
(count-package package-bag2 city-loc-11 pnum0)
(count-package package-bag2 city-loc-12 pnum0)
(count-package package-bag2 city-loc-13 pnum0)
(count-package package-bag2 city-loc-14 pnum0)
(count-package package-bag2 city-loc-15 pnum0)
(count-package package-bag2 city-loc-16 pnum0)
(count-package package-bag2 city-loc-17 pnum0)
(count-package package-bag2 city-loc-18 pnum0)
(count-package package-bag2 city-loc-19 pnum0)
(count-package package-bag2 city-loc-20 pnum0)
(count-package package-bag2 city-loc-21 pnum0)
(count-package package-bag2 city-loc-22 pnum0)
(count-package package-bag2 city-loc-23 pnum0)
(count-package package-bag2 city-loc-24 pnum0)
(count-package package-bag2 city-loc-25 pnum0)
(count-package package-bag2 city-loc-26 pnum0)
(count-package package-bag2 city-loc-27 pnum0)
(count-package package-bag2 city-loc-28 pnum0)
(count-package package-bag2 city-loc-29 pnum0)
(count-package package-bag2 city-loc-30 pnum0)
(count-package package-bag2 city-loc-31 pnum0)
(count-package package-bag2 city-loc-32 pnum0)
(count-package package-bag2 city-loc-33 pnum0)
(count-package package-bag2 city-loc-34 pnum0)
(count-package package-bag2 city-loc-36 pnum0)
(count-package package-bag2 city-loc-37 pnum0)
(count-package package-bag2 city-loc-38 pnum0)
(count-package package-bag2 city-loc-39 pnum0)
(count-package package-bag2 city-loc-40 pnum0)
(count-package package-bag2 city-loc-41 pnum0)
(count-package package-bag2 city-loc-42 pnum0)
(count-package package-bag2 city-loc-43 pnum0)
(count-package package-bag2 city-loc-44 pnum0)
(count-package package-bag2 city-loc-45 pnum0)
(count-package package-bag2 city-loc-46 pnum0)
(count-package package-bag2 city-loc-47 pnum0)
(count-package package-bag2 city-loc-48 pnum0)
(count-package package-bag2 city-loc-49 pnum0)
(count-package package-bag2 city-loc-50 pnum0)
(count-package package-bag2 city-loc-51 pnum0)
(count-package package-bag2 city-loc-52 pnum0)
(count-package package-bag2 city-loc-53 pnum0)
(count-package package-bag2 city-loc-54 pnum0)
(count-package package-bag2 city-loc-55 pnum0)
(count-package package-bag2 city-loc-56 pnum0)
(count-package package-bag2 city-loc-57 pnum0)
(count-package package-bag2 city-loc-58 pnum0)
(count-package package-bag2 city-loc-59 pnum0)
(count-package package-bag2 city-loc-60 pnum0)
(count-package package-bag2 city-loc-61 pnum0)
(count-package package-bag2 city-loc-62 pnum0)
(count-package package-bag2 city-loc-63 pnum0)
(count-package package-bag3 truck-1 pnum0)
(count-package package-bag3 truck-2 pnum0)
(count-package package-bag3 truck-3 pnum0)
(count-package package-bag3 truck-4 pnum0)
(count-package package-bag3 city-loc-1 pnum0)
(count-package package-bag3 city-loc-2 pnum0)
(count-package package-bag3 city-loc-3 pnum0)
(count-package package-bag3 city-loc-4 pnum0)
(count-package package-bag3 city-loc-5 pnum0)
(count-package package-bag3 city-loc-6 pnum0)
(count-package package-bag3 city-loc-7 pnum0)
(count-package package-bag3 city-loc-8 pnum0)
(count-package package-bag3 city-loc-9 pnum0)
(count-package package-bag3 city-loc-10 pnum0)
(count-package package-bag3 city-loc-11 pnum0)
(count-package package-bag3 city-loc-12 pnum0)
(count-package package-bag3 city-loc-13 pnum0)
(count-package package-bag3 city-loc-14 pnum0)
(count-package package-bag3 city-loc-15 pnum0)
(count-package package-bag3 city-loc-16 pnum0)
(count-package package-bag3 city-loc-17 pnum0)
(count-package package-bag3 city-loc-18 pnum0)
(count-package package-bag3 city-loc-19 pnum0)
(count-package package-bag3 city-loc-20 pnum0)
(count-package package-bag3 city-loc-21 pnum0)
(count-package package-bag3 city-loc-22 pnum0)
(count-package package-bag3 city-loc-23 pnum0)
(count-package package-bag3 city-loc-24 pnum0)
(count-package package-bag3 city-loc-25 pnum0)
(count-package package-bag3 city-loc-26 pnum0)
(count-package package-bag3 city-loc-27 pnum0)
(count-package package-bag3 city-loc-28 pnum0)
(count-package package-bag3 city-loc-29 pnum0)
(count-package package-bag3 city-loc-30 pnum0)
(count-package package-bag3 city-loc-31 pnum0)
(count-package package-bag3 city-loc-32 pnum0)
(count-package package-bag3 city-loc-33 pnum0)
(count-package package-bag3 city-loc-34 pnum0)
(count-package package-bag3 city-loc-35 pnum0)
(count-package package-bag3 city-loc-36 pnum0)
(count-package package-bag3 city-loc-37 pnum0)
(count-package package-bag3 city-loc-38 pnum0)
(count-package package-bag3 city-loc-39 pnum0)
(count-package package-bag3 city-loc-40 pnum0)
(count-package package-bag3 city-loc-41 pnum0)
(count-package package-bag3 city-loc-42 pnum0)
(count-package package-bag3 city-loc-43 pnum0)
(count-package package-bag3 city-loc-44 pnum0)
(count-package package-bag3 city-loc-45 pnum0)
(count-package package-bag3 city-loc-46 pnum0)
(count-package package-bag3 city-loc-47 pnum0)
(count-package package-bag3 city-loc-48 pnum0)
(count-package package-bag3 city-loc-49 pnum0)
(count-package package-bag3 city-loc-50 pnum0)
(count-package package-bag3 city-loc-51 pnum0)
(count-package package-bag3 city-loc-52 pnum0)
(count-package package-bag3 city-loc-53 pnum0)
(count-package package-bag3 city-loc-54 pnum0)
(count-package package-bag3 city-loc-56 pnum0)
(count-package package-bag3 city-loc-57 pnum0)
(count-package package-bag3 city-loc-58 pnum0)
(count-package package-bag3 city-loc-60 pnum0)
(count-package package-bag3 city-loc-61 pnum0)
(count-package package-bag3 city-loc-62 pnum0)
(count-package package-bag3 city-loc-63 pnum0)
(count-package package-bag4 truck-1 pnum0)
(count-package package-bag4 truck-2 pnum0)
(count-package package-bag4 truck-3 pnum0)
(count-package package-bag4 truck-4 pnum0)
(count-package package-bag4 city-loc-1 pnum0)
(count-package package-bag4 city-loc-2 pnum0)
(count-package package-bag4 city-loc-3 pnum0)
(count-package package-bag4 city-loc-4 pnum0)
(count-package package-bag4 city-loc-5 pnum0)
(count-package package-bag4 city-loc-6 pnum0)
(count-package package-bag4 city-loc-7 pnum0)
(count-package package-bag4 city-loc-8 pnum0)
(count-package package-bag4 city-loc-9 pnum0)
(count-package package-bag4 city-loc-10 pnum0)
(count-package package-bag4 city-loc-11 pnum0)
(count-package package-bag4 city-loc-12 pnum0)
(count-package package-bag4 city-loc-13 pnum0)
(count-package package-bag4 city-loc-14 pnum0)
(count-package package-bag4 city-loc-15 pnum0)
(count-package package-bag4 city-loc-16 pnum0)
(count-package package-bag4 city-loc-17 pnum0)
(count-package package-bag4 city-loc-18 pnum0)
(count-package package-bag4 city-loc-19 pnum0)
(count-package package-bag4 city-loc-20 pnum0)
(count-package package-bag4 city-loc-21 pnum0)
(count-package package-bag4 city-loc-23 pnum0)
(count-package package-bag4 city-loc-24 pnum0)
(count-package package-bag4 city-loc-25 pnum0)
(count-package package-bag4 city-loc-26 pnum0)
(count-package package-bag4 city-loc-27 pnum0)
(count-package package-bag4 city-loc-28 pnum0)
(count-package package-bag4 city-loc-29 pnum0)
(count-package package-bag4 city-loc-30 pnum0)
(count-package package-bag4 city-loc-31 pnum0)
(count-package package-bag4 city-loc-32 pnum0)
(count-package package-bag4 city-loc-33 pnum0)
(count-package package-bag4 city-loc-34 pnum0)
(count-package package-bag4 city-loc-35 pnum0)
(count-package package-bag4 city-loc-36 pnum0)
(count-package package-bag4 city-loc-37 pnum0)
(count-package package-bag4 city-loc-38 pnum0)
(count-package package-bag4 city-loc-39 pnum0)
(count-package package-bag4 city-loc-40 pnum0)
(count-package package-bag4 city-loc-41 pnum0)
(count-package package-bag4 city-loc-42 pnum0)
(count-package package-bag4 city-loc-43 pnum0)
(count-package package-bag4 city-loc-44 pnum0)
(count-package package-bag4 city-loc-45 pnum0)
(count-package package-bag4 city-loc-46 pnum0)
(count-package package-bag4 city-loc-48 pnum0)
(count-package package-bag4 city-loc-49 pnum0)
(count-package package-bag4 city-loc-50 pnum0)
(count-package package-bag4 city-loc-51 pnum0)
(count-package package-bag4 city-loc-52 pnum0)
(count-package package-bag4 city-loc-53 pnum0)
(count-package package-bag4 city-loc-54 pnum0)
(count-package package-bag4 city-loc-55 pnum0)
(count-package package-bag4 city-loc-56 pnum0)
(count-package package-bag4 city-loc-57 pnum0)
(count-package package-bag4 city-loc-58 pnum0)
(count-package package-bag4 city-loc-59 pnum0)
(count-package package-bag4 city-loc-60 pnum0)
(count-package package-bag4 city-loc-61 pnum0)
(count-package package-bag4 city-loc-62 pnum0)
(count-package package-bag4 city-loc-63 pnum0)
(count-package package-bag5 truck-1 pnum0)
(count-package package-bag5 truck-2 pnum0)
(count-package package-bag5 truck-3 pnum0)
(count-package package-bag5 truck-4 pnum0)
(count-package package-bag5 city-loc-1 pnum0)
(count-package package-bag5 city-loc-2 pnum0)
(count-package package-bag5 city-loc-3 pnum0)
(count-package package-bag5 city-loc-4 pnum0)
(count-package package-bag5 city-loc-5 pnum0)
(count-package package-bag5 city-loc-6 pnum0)
(count-package package-bag5 city-loc-7 pnum0)
(count-package package-bag5 city-loc-8 pnum0)
(count-package package-bag5 city-loc-10 pnum0)
(count-package package-bag5 city-loc-11 pnum0)
(count-package package-bag5 city-loc-12 pnum0)
(count-package package-bag5 city-loc-13 pnum0)
(count-package package-bag5 city-loc-14 pnum0)
(count-package package-bag5 city-loc-15 pnum0)
(count-package package-bag5 city-loc-17 pnum0)
(count-package package-bag5 city-loc-18 pnum0)
(count-package package-bag5 city-loc-19 pnum0)
(count-package package-bag5 city-loc-20 pnum0)
(count-package package-bag5 city-loc-21 pnum0)
(count-package package-bag5 city-loc-22 pnum0)
(count-package package-bag5 city-loc-23 pnum0)
(count-package package-bag5 city-loc-24 pnum0)
(count-package package-bag5 city-loc-25 pnum0)
(count-package package-bag5 city-loc-26 pnum0)
(count-package package-bag5 city-loc-27 pnum0)
(count-package package-bag5 city-loc-28 pnum0)
(count-package package-bag5 city-loc-29 pnum0)
(count-package package-bag5 city-loc-30 pnum0)
(count-package package-bag5 city-loc-31 pnum0)
(count-package package-bag5 city-loc-32 pnum0)
(count-package package-bag5 city-loc-33 pnum0)
(count-package package-bag5 city-loc-34 pnum0)
(count-package package-bag5 city-loc-35 pnum0)
(count-package package-bag5 city-loc-36 pnum0)
(count-package package-bag5 city-loc-37 pnum0)
(count-package package-bag5 city-loc-38 pnum0)
(count-package package-bag5 city-loc-39 pnum0)
(count-package package-bag5 city-loc-40 pnum0)
(count-package package-bag5 city-loc-41 pnum0)
(count-package package-bag5 city-loc-42 pnum0)
(count-package package-bag5 city-loc-43 pnum0)
(count-package package-bag5 city-loc-44 pnum0)
(count-package package-bag5 city-loc-45 pnum0)
(count-package package-bag5 city-loc-46 pnum0)
(count-package package-bag5 city-loc-47 pnum0)
(count-package package-bag5 city-loc-48 pnum0)
(count-package package-bag5 city-loc-49 pnum0)
(count-package package-bag5 city-loc-50 pnum0)
(count-package package-bag5 city-loc-51 pnum0)
(count-package package-bag5 city-loc-52 pnum0)
(count-package package-bag5 city-loc-53 pnum0)
(count-package package-bag5 city-loc-54 pnum0)
(count-package package-bag5 city-loc-55 pnum0)
(count-package package-bag5 city-loc-56 pnum0)
(count-package package-bag5 city-loc-57 pnum0)
(count-package package-bag5 city-loc-58 pnum0)
(count-package package-bag5 city-loc-59 pnum0)
(count-package package-bag5 city-loc-60 pnum0)
(count-package package-bag5 city-loc-61 pnum0)
(count-package package-bag5 city-loc-62 pnum0)
(count-package package-bag5 city-loc-63 pnum0)
(count-package package-bag6 truck-1 pnum0)
(count-package package-bag6 truck-2 pnum0)
(count-package package-bag6 truck-3 pnum0)
(count-package package-bag6 truck-4 pnum0)
(count-package package-bag6 city-loc-1 pnum0)
(count-package package-bag6 city-loc-2 pnum0)
(count-package package-bag6 city-loc-3 pnum0)
(count-package package-bag6 city-loc-4 pnum0)
(count-package package-bag6 city-loc-5 pnum0)
(count-package package-bag6 city-loc-6 pnum0)
(count-package package-bag6 city-loc-7 pnum0)
(count-package package-bag6 city-loc-8 pnum0)
(count-package package-bag6 city-loc-9 pnum0)
(count-package package-bag6 city-loc-10 pnum0)
(count-package package-bag6 city-loc-11 pnum0)
(count-package package-bag6 city-loc-12 pnum0)
(count-package package-bag6 city-loc-13 pnum0)
(count-package package-bag6 city-loc-14 pnum0)
(count-package package-bag6 city-loc-15 pnum0)
(count-package package-bag6 city-loc-16 pnum0)
(count-package package-bag6 city-loc-17 pnum0)
(count-package package-bag6 city-loc-18 pnum0)
(count-package package-bag6 city-loc-19 pnum0)
(count-package package-bag6 city-loc-21 pnum0)
(count-package package-bag6 city-loc-22 pnum0)
(count-package package-bag6 city-loc-23 pnum0)
(count-package package-bag6 city-loc-24 pnum0)
(count-package package-bag6 city-loc-25 pnum0)
(count-package package-bag6 city-loc-26 pnum0)
(count-package package-bag6 city-loc-27 pnum0)
(count-package package-bag6 city-loc-28 pnum0)
(count-package package-bag6 city-loc-29 pnum0)
(count-package package-bag6 city-loc-30 pnum0)
(count-package package-bag6 city-loc-31 pnum0)
(count-package package-bag6 city-loc-32 pnum0)
(count-package package-bag6 city-loc-33 pnum0)
(count-package package-bag6 city-loc-34 pnum0)
(count-package package-bag6 city-loc-35 pnum0)
(count-package package-bag6 city-loc-36 pnum0)
(count-package package-bag6 city-loc-37 pnum0)
(count-package package-bag6 city-loc-38 pnum0)
(count-package package-bag6 city-loc-39 pnum0)
(count-package package-bag6 city-loc-40 pnum0)
(count-package package-bag6 city-loc-41 pnum0)
(count-package package-bag6 city-loc-42 pnum0)
(count-package package-bag6 city-loc-43 pnum0)
(count-package package-bag6 city-loc-44 pnum0)
(count-package package-bag6 city-loc-45 pnum0)
(count-package package-bag6 city-loc-46 pnum0)
(count-package package-bag6 city-loc-47 pnum0)
(count-package package-bag6 city-loc-49 pnum0)
(count-package package-bag6 city-loc-50 pnum0)
(count-package package-bag6 city-loc-51 pnum0)
(count-package package-bag6 city-loc-52 pnum0)
(count-package package-bag6 city-loc-53 pnum0)
(count-package package-bag6 city-loc-54 pnum0)
(count-package package-bag6 city-loc-55 pnum0)
(count-package package-bag6 city-loc-56 pnum0)
(count-package package-bag6 city-loc-57 pnum0)
(count-package package-bag6 city-loc-58 pnum0)
(count-package package-bag6 city-loc-59 pnum0)
(count-package package-bag6 city-loc-60 pnum0)
(count-package package-bag6 city-loc-61 pnum0)
(count-package package-bag6 city-loc-62 pnum0)
(count-package package-bag6 city-loc-63 pnum0)
(count-package package-bag7 truck-1 pnum0)
(count-package package-bag7 truck-2 pnum0)
(count-package package-bag7 truck-3 pnum0)
(count-package package-bag7 truck-4 pnum0)
(count-package package-bag7 city-loc-1 pnum0)
(count-package package-bag7 city-loc-2 pnum0)
(count-package package-bag7 city-loc-3 pnum0)
(count-package package-bag7 city-loc-4 pnum0)
(count-package package-bag7 city-loc-5 pnum0)
(count-package package-bag7 city-loc-6 pnum0)
(count-package package-bag7 city-loc-7 pnum0)
(count-package package-bag7 city-loc-8 pnum0)
(count-package package-bag7 city-loc-9 pnum0)
(count-package package-bag7 city-loc-10 pnum0)
(count-package package-bag7 city-loc-11 pnum0)
(count-package package-bag7 city-loc-12 pnum0)
(count-package package-bag7 city-loc-13 pnum0)
(count-package package-bag7 city-loc-14 pnum0)
(count-package package-bag7 city-loc-15 pnum0)
(count-package package-bag7 city-loc-16 pnum0)
(count-package package-bag7 city-loc-17 pnum0)
(count-package package-bag7 city-loc-18 pnum0)
(count-package package-bag7 city-loc-20 pnum0)
(count-package package-bag7 city-loc-21 pnum0)
(count-package package-bag7 city-loc-22 pnum0)
(count-package package-bag7 city-loc-23 pnum0)
(count-package package-bag7 city-loc-24 pnum0)
(count-package package-bag7 city-loc-25 pnum0)
(count-package package-bag7 city-loc-26 pnum0)
(count-package package-bag7 city-loc-27 pnum0)
(count-package package-bag7 city-loc-28 pnum0)
(count-package package-bag7 city-loc-29 pnum0)
(count-package package-bag7 city-loc-30 pnum0)
(count-package package-bag7 city-loc-31 pnum0)
(count-package package-bag7 city-loc-32 pnum0)
(count-package package-bag7 city-loc-33 pnum0)
(count-package package-bag7 city-loc-34 pnum0)
(count-package package-bag7 city-loc-35 pnum0)
(count-package package-bag7 city-loc-36 pnum0)
(count-package package-bag7 city-loc-37 pnum0)
(count-package package-bag7 city-loc-38 pnum0)
(count-package package-bag7 city-loc-39 pnum0)
(count-package package-bag7 city-loc-40 pnum0)
(count-package package-bag7 city-loc-41 pnum0)
(count-package package-bag7 city-loc-42 pnum0)
(count-package package-bag7 city-loc-43 pnum0)
(count-package package-bag7 city-loc-44 pnum0)
(count-package package-bag7 city-loc-45 pnum0)
(count-package package-bag7 city-loc-46 pnum0)
(count-package package-bag7 city-loc-47 pnum0)
(count-package package-bag7 city-loc-48 pnum0)
(count-package package-bag7 city-loc-49 pnum0)
(count-package package-bag7 city-loc-50 pnum0)
(count-package package-bag7 city-loc-51 pnum0)
(count-package package-bag7 city-loc-52 pnum0)
(count-package package-bag7 city-loc-53 pnum0)
(count-package package-bag7 city-loc-54 pnum0)
(count-package package-bag7 city-loc-55 pnum0)
(count-package package-bag7 city-loc-56 pnum0)
(count-package package-bag7 city-loc-57 pnum0)
(count-package package-bag7 city-loc-58 pnum0)
(count-package package-bag7 city-loc-59 pnum0)
(count-package package-bag7 city-loc-60 pnum0)
(count-package package-bag7 city-loc-61 pnum0)
(count-package package-bag7 city-loc-62 pnum0)
(count-package package-bag7 city-loc-63 pnum0)
(count-package package-bag8 truck-1 pnum0)
(count-package package-bag8 truck-2 pnum0)
(count-package package-bag8 truck-3 pnum0)
(count-package package-bag8 truck-4 pnum0)
(count-package package-bag8 city-loc-1 pnum0)
(count-package package-bag8 city-loc-2 pnum0)
(count-package package-bag8 city-loc-3 pnum0)
(count-package package-bag8 city-loc-4 pnum0)
(count-package package-bag8 city-loc-5 pnum0)
(count-package package-bag8 city-loc-6 pnum0)
(count-package package-bag8 city-loc-7 pnum0)
(count-package package-bag8 city-loc-8 pnum0)
(count-package package-bag8 city-loc-9 pnum0)
(count-package package-bag8 city-loc-10 pnum0)
(count-package package-bag8 city-loc-11 pnum0)
(count-package package-bag8 city-loc-12 pnum0)
(count-package package-bag8 city-loc-13 pnum0)
(count-package package-bag8 city-loc-14 pnum0)
(count-package package-bag8 city-loc-15 pnum0)
(count-package package-bag8 city-loc-16 pnum0)
(count-package package-bag8 city-loc-17 pnum0)
(count-package package-bag8 city-loc-18 pnum0)
(count-package package-bag8 city-loc-19 pnum0)
(count-package package-bag8 city-loc-20 pnum0)
(count-package package-bag8 city-loc-21 pnum0)
(count-package package-bag8 city-loc-22 pnum0)
(count-package package-bag8 city-loc-23 pnum0)
(count-package package-bag8 city-loc-24 pnum0)
(count-package package-bag8 city-loc-25 pnum0)
(count-package package-bag8 city-loc-26 pnum0)
(count-package package-bag8 city-loc-27 pnum0)
(count-package package-bag8 city-loc-28 pnum0)
(count-package package-bag8 city-loc-29 pnum0)
(count-package package-bag8 city-loc-30 pnum0)
(count-package package-bag8 city-loc-31 pnum0)
(count-package package-bag8 city-loc-32 pnum0)
(count-package package-bag8 city-loc-33 pnum0)
(count-package package-bag8 city-loc-34 pnum0)
(count-package package-bag8 city-loc-36 pnum0)
(count-package package-bag8 city-loc-37 pnum0)
(count-package package-bag8 city-loc-38 pnum0)
(count-package package-bag8 city-loc-39 pnum0)
(count-package package-bag8 city-loc-40 pnum0)
(count-package package-bag8 city-loc-41 pnum0)
(count-package package-bag8 city-loc-42 pnum0)
(count-package package-bag8 city-loc-43 pnum0)
(count-package package-bag8 city-loc-44 pnum0)
(count-package package-bag8 city-loc-45 pnum0)
(count-package package-bag8 city-loc-46 pnum0)
(count-package package-bag8 city-loc-47 pnum0)
(count-package package-bag8 city-loc-48 pnum0)
(count-package package-bag8 city-loc-49 pnum0)
(count-package package-bag8 city-loc-50 pnum0)
(count-package package-bag8 city-loc-51 pnum0)
(count-package package-bag8 city-loc-52 pnum0)
(count-package package-bag8 city-loc-53 pnum0)
(count-package package-bag8 city-loc-54 pnum0)
(count-package package-bag8 city-loc-55 pnum0)
(count-package package-bag8 city-loc-56 pnum0)
(count-package package-bag8 city-loc-57 pnum0)
(count-package package-bag8 city-loc-58 pnum0)
(count-package package-bag8 city-loc-59 pnum0)
(count-package package-bag8 city-loc-60 pnum0)
(count-package package-bag8 city-loc-61 pnum0)
(count-package package-bag8 city-loc-62 pnum0)
(count-package package-bag8 city-loc-63 pnum0)
(count-package package-bag9 truck-1 pnum0)
(count-package package-bag9 truck-2 pnum0)
(count-package package-bag9 truck-3 pnum0)
(count-package package-bag9 truck-4 pnum0)
(count-package package-bag9 city-loc-1 pnum0)
(count-package package-bag9 city-loc-2 pnum0)
(count-package package-bag9 city-loc-3 pnum0)
(count-package package-bag9 city-loc-5 pnum0)
(count-package package-bag9 city-loc-6 pnum0)
(count-package package-bag9 city-loc-7 pnum0)
(count-package package-bag9 city-loc-8 pnum0)
(count-package package-bag9 city-loc-9 pnum0)
(count-package package-bag9 city-loc-10 pnum0)
(count-package package-bag9 city-loc-11 pnum0)
(count-package package-bag9 city-loc-12 pnum0)
(count-package package-bag9 city-loc-13 pnum0)
(count-package package-bag9 city-loc-14 pnum0)
(count-package package-bag9 city-loc-15 pnum0)
(count-package package-bag9 city-loc-16 pnum0)
(count-package package-bag9 city-loc-17 pnum0)
(count-package package-bag9 city-loc-18 pnum0)
(count-package package-bag9 city-loc-19 pnum0)
(count-package package-bag9 city-loc-20 pnum0)
(count-package package-bag9 city-loc-21 pnum0)
(count-package package-bag9 city-loc-22 pnum0)
(count-package package-bag9 city-loc-23 pnum0)
(count-package package-bag9 city-loc-24 pnum0)
(count-package package-bag9 city-loc-25 pnum0)
(count-package package-bag9 city-loc-26 pnum0)
(count-package package-bag9 city-loc-27 pnum0)
(count-package package-bag9 city-loc-28 pnum0)
(count-package package-bag9 city-loc-29 pnum0)
(count-package package-bag9 city-loc-30 pnum0)
(count-package package-bag9 city-loc-31 pnum0)
(count-package package-bag9 city-loc-32 pnum0)
(count-package package-bag9 city-loc-33 pnum0)
(count-package package-bag9 city-loc-34 pnum0)
(count-package package-bag9 city-loc-35 pnum0)
(count-package package-bag9 city-loc-36 pnum0)
(count-package package-bag9 city-loc-37 pnum0)
(count-package package-bag9 city-loc-38 pnum0)
(count-package package-bag9 city-loc-39 pnum0)
(count-package package-bag9 city-loc-40 pnum0)
(count-package package-bag9 city-loc-41 pnum0)
(count-package package-bag9 city-loc-42 pnum0)
(count-package package-bag9 city-loc-43 pnum0)
(count-package package-bag9 city-loc-44 pnum0)
(count-package package-bag9 city-loc-45 pnum0)
(count-package package-bag9 city-loc-46 pnum0)
(count-package package-bag9 city-loc-47 pnum0)
(count-package package-bag9 city-loc-48 pnum0)
(count-package package-bag9 city-loc-49 pnum0)
(count-package package-bag9 city-loc-50 pnum0)
(count-package package-bag9 city-loc-51 pnum0)
(count-package package-bag9 city-loc-52 pnum0)
(count-package package-bag9 city-loc-53 pnum0)
(count-package package-bag9 city-loc-54 pnum0)
(count-package package-bag9 city-loc-55 pnum0)
(count-package package-bag9 city-loc-56 pnum0)
(count-package package-bag9 city-loc-57 pnum0)
(count-package package-bag9 city-loc-58 pnum0)
(count-package package-bag9 city-loc-59 pnum0)
(count-package package-bag9 city-loc-60 pnum0)
(count-package package-bag9 city-loc-61 pnum0)
(count-package package-bag9 city-loc-62 pnum0)
(count-package package-bag9 city-loc-63 pnum0)
(count-package package-bag10 truck-1 pnum0)
(count-package package-bag10 truck-2 pnum0)
(count-package package-bag10 truck-3 pnum0)
(count-package package-bag10 truck-4 pnum0)
(count-package package-bag10 city-loc-1 pnum0)
(count-package package-bag10 city-loc-2 pnum0)
(count-package package-bag10 city-loc-3 pnum0)
(count-package package-bag10 city-loc-4 pnum0)
(count-package package-bag10 city-loc-6 pnum0)
(count-package package-bag10 city-loc-7 pnum0)
(count-package package-bag10 city-loc-8 pnum0)
(count-package package-bag10 city-loc-9 pnum0)
(count-package package-bag10 city-loc-10 pnum0)
(count-package package-bag10 city-loc-11 pnum0)
(count-package package-bag10 city-loc-12 pnum0)
(count-package package-bag10 city-loc-13 pnum0)
(count-package package-bag10 city-loc-14 pnum0)
(count-package package-bag10 city-loc-15 pnum0)
(count-package package-bag10 city-loc-16 pnum0)
(count-package package-bag10 city-loc-17 pnum0)
(count-package package-bag10 city-loc-18 pnum0)
(count-package package-bag10 city-loc-19 pnum0)
(count-package package-bag10 city-loc-20 pnum0)
(count-package package-bag10 city-loc-21 pnum0)
(count-package package-bag10 city-loc-22 pnum0)
(count-package package-bag10 city-loc-23 pnum0)
(count-package package-bag10 city-loc-24 pnum0)
(count-package package-bag10 city-loc-25 pnum0)
(count-package package-bag10 city-loc-26 pnum0)
(count-package package-bag10 city-loc-27 pnum0)
(count-package package-bag10 city-loc-28 pnum0)
(count-package package-bag10 city-loc-29 pnum0)
(count-package package-bag10 city-loc-30 pnum0)
(count-package package-bag10 city-loc-31 pnum0)
(count-package package-bag10 city-loc-32 pnum0)
(count-package package-bag10 city-loc-33 pnum0)
(count-package package-bag10 city-loc-34 pnum0)
(count-package package-bag10 city-loc-35 pnum0)
(count-package package-bag10 city-loc-36 pnum0)
(count-package package-bag10 city-loc-37 pnum0)
(count-package package-bag10 city-loc-38 pnum0)
(count-package package-bag10 city-loc-39 pnum0)
(count-package package-bag10 city-loc-40 pnum0)
(count-package package-bag10 city-loc-41 pnum0)
(count-package package-bag10 city-loc-42 pnum0)
(count-package package-bag10 city-loc-43 pnum0)
(count-package package-bag10 city-loc-44 pnum0)
(count-package package-bag10 city-loc-45 pnum0)
(count-package package-bag10 city-loc-46 pnum0)
(count-package package-bag10 city-loc-47 pnum0)
(count-package package-bag10 city-loc-48 pnum0)
(count-package package-bag10 city-loc-49 pnum0)
(count-package package-bag10 city-loc-50 pnum0)
(count-package package-bag10 city-loc-51 pnum0)
(count-package package-bag10 city-loc-52 pnum0)
(count-package package-bag10 city-loc-53 pnum0)
(count-package package-bag10 city-loc-54 pnum0)
(count-package package-bag10 city-loc-55 pnum0)
(count-package package-bag10 city-loc-56 pnum0)
(count-package package-bag10 city-loc-57 pnum0)
(count-package package-bag10 city-loc-58 pnum0)
(count-package package-bag10 city-loc-59 pnum0)
(count-package package-bag10 city-loc-60 pnum0)
(count-package package-bag10 city-loc-61 pnum0)
(count-package package-bag10 city-loc-62 pnum0)
(count-package package-bag10 city-loc-63 pnum0)
(count-package package-bag11 truck-1 pnum0)
(count-package package-bag11 truck-2 pnum0)
(count-package package-bag11 truck-3 pnum0)
(count-package package-bag11 truck-4 pnum0)
(count-package package-bag11 city-loc-1 pnum0)
(count-package package-bag11 city-loc-2 pnum0)
(count-package package-bag11 city-loc-3 pnum0)
(count-package package-bag11 city-loc-4 pnum0)
(count-package package-bag11 city-loc-5 pnum0)
(count-package package-bag11 city-loc-6 pnum0)
(count-package package-bag11 city-loc-7 pnum0)
(count-package package-bag11 city-loc-8 pnum0)
(count-package package-bag11 city-loc-9 pnum0)
(count-package package-bag11 city-loc-10 pnum0)
(count-package package-bag11 city-loc-11 pnum0)
(count-package package-bag11 city-loc-12 pnum0)
(count-package package-bag11 city-loc-13 pnum0)
(count-package package-bag11 city-loc-14 pnum0)
(count-package package-bag11 city-loc-15 pnum0)
(count-package package-bag11 city-loc-16 pnum0)
(count-package package-bag11 city-loc-17 pnum0)
(count-package package-bag11 city-loc-18 pnum0)
(count-package package-bag11 city-loc-19 pnum0)
(count-package package-bag11 city-loc-20 pnum0)
(count-package package-bag11 city-loc-21 pnum0)
(count-package package-bag11 city-loc-22 pnum0)
(count-package package-bag11 city-loc-23 pnum0)
(count-package package-bag11 city-loc-24 pnum0)
(count-package package-bag11 city-loc-25 pnum0)
(count-package package-bag11 city-loc-26 pnum0)
(count-package package-bag11 city-loc-27 pnum0)
(count-package package-bag11 city-loc-28 pnum0)
(count-package package-bag11 city-loc-29 pnum0)
(count-package package-bag11 city-loc-30 pnum0)
(count-package package-bag11 city-loc-31 pnum0)
(count-package package-bag11 city-loc-32 pnum0)
(count-package package-bag11 city-loc-33 pnum0)
(count-package package-bag11 city-loc-34 pnum0)
(count-package package-bag11 city-loc-35 pnum0)
(count-package package-bag11 city-loc-36 pnum0)
(count-package package-bag11 city-loc-37 pnum0)
(count-package package-bag11 city-loc-38 pnum0)
(count-package package-bag11 city-loc-39 pnum0)
(count-package package-bag11 city-loc-40 pnum0)
(count-package package-bag11 city-loc-41 pnum0)
(count-package package-bag11 city-loc-42 pnum0)
(count-package package-bag11 city-loc-43 pnum0)
(count-package package-bag11 city-loc-44 pnum0)
(count-package package-bag11 city-loc-45 pnum0)
(count-package package-bag11 city-loc-46 pnum0)
(count-package package-bag11 city-loc-47 pnum0)
(count-package package-bag11 city-loc-48 pnum0)
(count-package package-bag11 city-loc-49 pnum0)
(count-package package-bag11 city-loc-50 pnum0)
(count-package package-bag11 city-loc-51 pnum0)
(count-package package-bag11 city-loc-52 pnum0)
(count-package package-bag11 city-loc-53 pnum0)
(count-package package-bag11 city-loc-54 pnum0)
(count-package package-bag11 city-loc-55 pnum0)
(count-package package-bag11 city-loc-56 pnum0)
(count-package package-bag11 city-loc-57 pnum0)
(count-package package-bag11 city-loc-59 pnum0)
(count-package package-bag11 city-loc-60 pnum0)
(count-package package-bag11 city-loc-61 pnum0)
(count-package package-bag11 city-loc-62 pnum0)
(count-package package-bag11 city-loc-63 pnum0)
(count-package package-bag12 truck-1 pnum0)
(count-package package-bag12 truck-2 pnum0)
(count-package package-bag12 truck-3 pnum0)
(count-package package-bag12 truck-4 pnum0)
(count-package package-bag12 city-loc-1 pnum0)
(count-package package-bag12 city-loc-2 pnum0)
(count-package package-bag12 city-loc-3 pnum0)
(count-package package-bag12 city-loc-4 pnum0)
(count-package package-bag12 city-loc-5 pnum0)
(count-package package-bag12 city-loc-6 pnum0)
(count-package package-bag12 city-loc-7 pnum0)
(count-package package-bag12 city-loc-8 pnum0)
(count-package package-bag12 city-loc-9 pnum0)
(count-package package-bag12 city-loc-10 pnum0)
(count-package package-bag12 city-loc-11 pnum0)
(count-package package-bag12 city-loc-12 pnum0)
(count-package package-bag12 city-loc-13 pnum0)
(count-package package-bag12 city-loc-14 pnum0)
(count-package package-bag12 city-loc-15 pnum0)
(count-package package-bag12 city-loc-16 pnum0)
(count-package package-bag12 city-loc-17 pnum0)
(count-package package-bag12 city-loc-18 pnum0)
(count-package package-bag12 city-loc-19 pnum0)
(count-package package-bag12 city-loc-20 pnum0)
(count-package package-bag12 city-loc-21 pnum0)
(count-package package-bag12 city-loc-22 pnum0)
(count-package package-bag12 city-loc-23 pnum0)
(count-package package-bag12 city-loc-24 pnum0)
(count-package package-bag12 city-loc-25 pnum0)
(count-package package-bag12 city-loc-26 pnum0)
(count-package package-bag12 city-loc-27 pnum0)
(count-package package-bag12 city-loc-28 pnum0)
(count-package package-bag12 city-loc-29 pnum0)
(count-package package-bag12 city-loc-30 pnum0)
(count-package package-bag12 city-loc-31 pnum0)
(count-package package-bag12 city-loc-32 pnum0)
(count-package package-bag12 city-loc-34 pnum0)
(count-package package-bag12 city-loc-35 pnum0)
(count-package package-bag12 city-loc-36 pnum0)
(count-package package-bag12 city-loc-37 pnum0)
(count-package package-bag12 city-loc-38 pnum0)
(count-package package-bag12 city-loc-39 pnum0)
(count-package package-bag12 city-loc-40 pnum0)
(count-package package-bag12 city-loc-41 pnum0)
(count-package package-bag12 city-loc-42 pnum0)
(count-package package-bag12 city-loc-43 pnum0)
(count-package package-bag12 city-loc-44 pnum0)
(count-package package-bag12 city-loc-45 pnum0)
(count-package package-bag12 city-loc-46 pnum0)
(count-package package-bag12 city-loc-47 pnum0)
(count-package package-bag12 city-loc-48 pnum0)
(count-package package-bag12 city-loc-49 pnum0)
(count-package package-bag12 city-loc-50 pnum0)
(count-package package-bag12 city-loc-51 pnum0)
(count-package package-bag12 city-loc-52 pnum0)
(count-package package-bag12 city-loc-53 pnum0)
(count-package package-bag12 city-loc-54 pnum0)
(count-package package-bag12 city-loc-55 pnum0)
(count-package package-bag12 city-loc-56 pnum0)
(count-package package-bag12 city-loc-57 pnum0)
(count-package package-bag12 city-loc-58 pnum0)
(count-package package-bag12 city-loc-59 pnum0)
(count-package package-bag12 city-loc-60 pnum0)
(count-package package-bag12 city-loc-61 pnum0)
(count-package package-bag12 city-loc-62 pnum0)
(count-package package-bag12 city-loc-63 pnum0)
(count-package package-bag13 truck-1 pnum0)
(count-package package-bag13 truck-2 pnum0)
(count-package package-bag13 truck-3 pnum0)
(count-package package-bag13 truck-4 pnum0)
(count-package package-bag13 city-loc-1 pnum0)
(count-package package-bag13 city-loc-2 pnum0)
(count-package package-bag13 city-loc-3 pnum0)
(count-package package-bag13 city-loc-4 pnum0)
(count-package package-bag13 city-loc-5 pnum0)
(count-package package-bag13 city-loc-6 pnum0)
(count-package package-bag13 city-loc-7 pnum0)
(count-package package-bag13 city-loc-8 pnum0)
(count-package package-bag13 city-loc-9 pnum0)
(count-package package-bag13 city-loc-10 pnum0)
(count-package package-bag13 city-loc-11 pnum0)
(count-package package-bag13 city-loc-12 pnum0)
(count-package package-bag13 city-loc-14 pnum0)
(count-package package-bag13 city-loc-15 pnum0)
(count-package package-bag13 city-loc-16 pnum0)
(count-package package-bag13 city-loc-17 pnum0)
(count-package package-bag13 city-loc-18 pnum0)
(count-package package-bag13 city-loc-19 pnum0)
(count-package package-bag13 city-loc-20 pnum0)
(count-package package-bag13 city-loc-21 pnum0)
(count-package package-bag13 city-loc-22 pnum0)
(count-package package-bag13 city-loc-23 pnum0)
(count-package package-bag13 city-loc-24 pnum0)
(count-package package-bag13 city-loc-25 pnum0)
(count-package package-bag13 city-loc-26 pnum0)
(count-package package-bag13 city-loc-27 pnum0)
(count-package package-bag13 city-loc-28 pnum0)
(count-package package-bag13 city-loc-29 pnum0)
(count-package package-bag13 city-loc-30 pnum0)
(count-package package-bag13 city-loc-31 pnum0)
(count-package package-bag13 city-loc-32 pnum0)
(count-package package-bag13 city-loc-33 pnum0)
(count-package package-bag13 city-loc-34 pnum0)
(count-package package-bag13 city-loc-35 pnum0)
(count-package package-bag13 city-loc-36 pnum0)
(count-package package-bag13 city-loc-37 pnum0)
(count-package package-bag13 city-loc-38 pnum0)
(count-package package-bag13 city-loc-39 pnum0)
(count-package package-bag13 city-loc-40 pnum0)
(count-package package-bag13 city-loc-41 pnum0)
(count-package package-bag13 city-loc-42 pnum0)
(count-package package-bag13 city-loc-43 pnum0)
(count-package package-bag13 city-loc-44 pnum0)
(count-package package-bag13 city-loc-45 pnum0)
(count-package package-bag13 city-loc-46 pnum0)
(count-package package-bag13 city-loc-47 pnum0)
(count-package package-bag13 city-loc-48 pnum0)
(count-package package-bag13 city-loc-49 pnum0)
(count-package package-bag13 city-loc-50 pnum0)
(count-package package-bag13 city-loc-51 pnum0)
(count-package package-bag13 city-loc-52 pnum0)
(count-package package-bag13 city-loc-53 pnum0)
(count-package package-bag13 city-loc-54 pnum0)
(count-package package-bag13 city-loc-55 pnum0)
(count-package package-bag13 city-loc-56 pnum0)
(count-package package-bag13 city-loc-57 pnum0)
(count-package package-bag13 city-loc-58 pnum0)
(count-package package-bag13 city-loc-59 pnum0)
(count-package package-bag13 city-loc-60 pnum0)
(count-package package-bag13 city-loc-61 pnum0)
(count-package package-bag13 city-loc-62 pnum0)
(count-package package-bag13 city-loc-63 pnum0)
(count-package package-bag14 truck-1 pnum0)
(count-package package-bag14 truck-2 pnum0)
(count-package package-bag14 truck-3 pnum0)
(count-package package-bag14 truck-4 pnum0)
(count-package package-bag14 city-loc-1 pnum0)
(count-package package-bag14 city-loc-2 pnum0)
(count-package package-bag14 city-loc-3 pnum0)
(count-package package-bag14 city-loc-4 pnum0)
(count-package package-bag14 city-loc-5 pnum0)
(count-package package-bag14 city-loc-6 pnum0)
(count-package package-bag14 city-loc-7 pnum0)
(count-package package-bag14 city-loc-8 pnum0)
(count-package package-bag14 city-loc-9 pnum0)
(count-package package-bag14 city-loc-10 pnum0)
(count-package package-bag14 city-loc-11 pnum0)
(count-package package-bag14 city-loc-12 pnum0)
(count-package package-bag14 city-loc-13 pnum0)
(count-package package-bag14 city-loc-14 pnum0)
(count-package package-bag14 city-loc-15 pnum0)
(count-package package-bag14 city-loc-16 pnum0)
(count-package package-bag14 city-loc-17 pnum0)
(count-package package-bag14 city-loc-18 pnum0)
(count-package package-bag14 city-loc-19 pnum0)
(count-package package-bag14 city-loc-20 pnum0)
(count-package package-bag14 city-loc-21 pnum0)
(count-package package-bag14 city-loc-22 pnum0)
(count-package package-bag14 city-loc-23 pnum0)
(count-package package-bag14 city-loc-24 pnum0)
(count-package package-bag14 city-loc-25 pnum0)
(count-package package-bag14 city-loc-26 pnum0)
(count-package package-bag14 city-loc-27 pnum0)
(count-package package-bag14 city-loc-28 pnum0)
(count-package package-bag14 city-loc-29 pnum0)
(count-package package-bag14 city-loc-30 pnum0)
(count-package package-bag14 city-loc-31 pnum0)
(count-package package-bag14 city-loc-32 pnum0)
(count-package package-bag14 city-loc-33 pnum0)
(count-package package-bag14 city-loc-34 pnum0)
(count-package package-bag14 city-loc-35 pnum0)
(count-package package-bag14 city-loc-36 pnum0)
(count-package package-bag14 city-loc-37 pnum0)
(count-package package-bag14 city-loc-38 pnum0)
(count-package package-bag14 city-loc-39 pnum0)
(count-package package-bag14 city-loc-40 pnum0)
(count-package package-bag14 city-loc-41 pnum0)
(count-package package-bag14 city-loc-42 pnum0)
(count-package package-bag14 city-loc-43 pnum0)
(count-package package-bag14 city-loc-44 pnum0)
(count-package package-bag14 city-loc-45 pnum0)
(count-package package-bag14 city-loc-46 pnum0)
(count-package package-bag14 city-loc-47 pnum0)
(count-package package-bag14 city-loc-48 pnum0)
(count-package package-bag14 city-loc-49 pnum0)
(count-package package-bag14 city-loc-50 pnum0)
(count-package package-bag14 city-loc-51 pnum0)
(count-package package-bag14 city-loc-52 pnum0)
(count-package package-bag14 city-loc-53 pnum0)
(count-package package-bag14 city-loc-54 pnum0)
(count-package package-bag14 city-loc-55 pnum0)
(count-package package-bag14 city-loc-56 pnum0)
(count-package package-bag14 city-loc-57 pnum0)
(count-package package-bag14 city-loc-58 pnum0)
(count-package package-bag14 city-loc-59 pnum0)
(count-package package-bag14 city-loc-60 pnum0)
(count-package package-bag14 city-loc-61 pnum0)
(count-package package-bag14 city-loc-63 pnum0)
(count-package package-bag15 truck-1 pnum0)
(count-package package-bag15 truck-2 pnum0)
(count-package package-bag15 truck-3 pnum0)
(count-package package-bag15 truck-4 pnum0)
(count-package package-bag15 city-loc-1 pnum0)
(count-package package-bag15 city-loc-2 pnum0)
(count-package package-bag15 city-loc-3 pnum0)
(count-package package-bag15 city-loc-4 pnum0)
(count-package package-bag15 city-loc-5 pnum0)
(count-package package-bag15 city-loc-6 pnum0)
(count-package package-bag15 city-loc-7 pnum0)
(count-package package-bag15 city-loc-8 pnum0)
(count-package package-bag15 city-loc-9 pnum0)
(count-package package-bag15 city-loc-10 pnum0)
(count-package package-bag15 city-loc-11 pnum0)
(count-package package-bag15 city-loc-12 pnum0)
(count-package package-bag15 city-loc-13 pnum0)
(count-package package-bag15 city-loc-14 pnum0)
(count-package package-bag15 city-loc-15 pnum0)
(count-package package-bag15 city-loc-16 pnum0)
(count-package package-bag15 city-loc-17 pnum0)
(count-package package-bag15 city-loc-18 pnum0)
(count-package package-bag15 city-loc-19 pnum0)
(count-package package-bag15 city-loc-20 pnum0)
(count-package package-bag15 city-loc-21 pnum0)
(count-package package-bag15 city-loc-23 pnum0)
(count-package package-bag15 city-loc-24 pnum0)
(count-package package-bag15 city-loc-25 pnum0)
(count-package package-bag15 city-loc-26 pnum0)
(count-package package-bag15 city-loc-27 pnum0)
(count-package package-bag15 city-loc-28 pnum0)
(count-package package-bag15 city-loc-29 pnum0)
(count-package package-bag15 city-loc-30 pnum0)
(count-package package-bag15 city-loc-31 pnum0)
(count-package package-bag15 city-loc-32 pnum0)
(count-package package-bag15 city-loc-33 pnum0)
(count-package package-bag15 city-loc-34 pnum0)
(count-package package-bag15 city-loc-35 pnum0)
(count-package package-bag15 city-loc-36 pnum0)
(count-package package-bag15 city-loc-37 pnum0)
(count-package package-bag15 city-loc-38 pnum0)
(count-package package-bag15 city-loc-39 pnum0)
(count-package package-bag15 city-loc-40 pnum0)
(count-package package-bag15 city-loc-41 pnum0)
(count-package package-bag15 city-loc-42 pnum0)
(count-package package-bag15 city-loc-43 pnum0)
(count-package package-bag15 city-loc-44 pnum0)
(count-package package-bag15 city-loc-45 pnum0)
(count-package package-bag15 city-loc-46 pnum0)
(count-package package-bag15 city-loc-47 pnum0)
(count-package package-bag15 city-loc-48 pnum0)
(count-package package-bag15 city-loc-49 pnum0)
(count-package package-bag15 city-loc-50 pnum0)
(count-package package-bag15 city-loc-51 pnum0)
(count-package package-bag15 city-loc-52 pnum0)
(count-package package-bag15 city-loc-53 pnum0)
(count-package package-bag15 city-loc-54 pnum0)
(count-package package-bag15 city-loc-55 pnum0)
(count-package package-bag15 city-loc-56 pnum0)
(count-package package-bag15 city-loc-57 pnum0)
(count-package package-bag15 city-loc-58 pnum0)
(count-package package-bag15 city-loc-59 pnum0)
(count-package package-bag15 city-loc-60 pnum0)
(count-package package-bag15 city-loc-61 pnum0)
(count-package package-bag15 city-loc-62 pnum0)
(count-package package-bag15 city-loc-63 pnum0)
(count-package package-bag16 truck-1 pnum0)
(count-package package-bag16 truck-2 pnum0)
(count-package package-bag16 truck-3 pnum0)
(count-package package-bag16 truck-4 pnum0)
(count-package package-bag16 city-loc-1 pnum0)
(count-package package-bag16 city-loc-2 pnum0)
(count-package package-bag16 city-loc-3 pnum0)
(count-package package-bag16 city-loc-4 pnum0)
(count-package package-bag16 city-loc-5 pnum0)
(count-package package-bag16 city-loc-6 pnum0)
(count-package package-bag16 city-loc-7 pnum0)
(count-package package-bag16 city-loc-8 pnum0)
(count-package package-bag16 city-loc-9 pnum0)
(count-package package-bag16 city-loc-10 pnum0)
(count-package package-bag16 city-loc-11 pnum0)
(count-package package-bag16 city-loc-12 pnum0)
(count-package package-bag16 city-loc-13 pnum0)
(count-package package-bag16 city-loc-14 pnum0)
(count-package package-bag16 city-loc-15 pnum0)
(count-package package-bag16 city-loc-16 pnum0)
(count-package package-bag16 city-loc-17 pnum0)
(count-package package-bag16 city-loc-18 pnum0)
(count-package package-bag16 city-loc-19 pnum0)
(count-package package-bag16 city-loc-20 pnum0)
(count-package package-bag16 city-loc-21 pnum0)
(count-package package-bag16 city-loc-22 pnum0)
(count-package package-bag16 city-loc-23 pnum0)
(count-package package-bag16 city-loc-24 pnum0)
(count-package package-bag16 city-loc-25 pnum0)
(count-package package-bag16 city-loc-26 pnum0)
(count-package package-bag16 city-loc-27 pnum0)
(count-package package-bag16 city-loc-28 pnum0)
(count-package package-bag16 city-loc-29 pnum0)
(count-package package-bag16 city-loc-30 pnum0)
(count-package package-bag16 city-loc-31 pnum0)
(count-package package-bag16 city-loc-32 pnum0)
(count-package package-bag16 city-loc-33 pnum0)
(count-package package-bag16 city-loc-34 pnum0)
(count-package package-bag16 city-loc-35 pnum0)
(count-package package-bag16 city-loc-36 pnum0)
(count-package package-bag16 city-loc-37 pnum0)
(count-package package-bag16 city-loc-38 pnum0)
(count-package package-bag16 city-loc-39 pnum0)
(count-package package-bag16 city-loc-40 pnum0)
(count-package package-bag16 city-loc-42 pnum0)
(count-package package-bag16 city-loc-43 pnum0)
(count-package package-bag16 city-loc-44 pnum0)
(count-package package-bag16 city-loc-45 pnum0)
(count-package package-bag16 city-loc-46 pnum0)
(count-package package-bag16 city-loc-47 pnum0)
(count-package package-bag16 city-loc-48 pnum0)
(count-package package-bag16 city-loc-49 pnum0)
(count-package package-bag16 city-loc-50 pnum0)
(count-package package-bag16 city-loc-51 pnum0)
(count-package package-bag16 city-loc-52 pnum0)
(count-package package-bag16 city-loc-53 pnum0)
(count-package package-bag16 city-loc-54 pnum0)
(count-package package-bag16 city-loc-55 pnum0)
(count-package package-bag16 city-loc-56 pnum0)
(count-package package-bag16 city-loc-57 pnum0)
(count-package package-bag16 city-loc-58 pnum0)
(count-package package-bag16 city-loc-59 pnum0)
(count-package package-bag16 city-loc-60 pnum0)
(count-package package-bag16 city-loc-61 pnum0)
(count-package package-bag16 city-loc-62 pnum0)
(count-package package-bag16 city-loc-63 pnum0)
(count-package package-bag17 truck-1 pnum0)
(count-package package-bag17 truck-2 pnum0)
(count-package package-bag17 truck-3 pnum0)
(count-package package-bag17 truck-4 pnum0)
(count-package package-bag17 city-loc-1 pnum0)
(count-package package-bag17 city-loc-2 pnum0)
(count-package package-bag17 city-loc-3 pnum0)
(count-package package-bag17 city-loc-4 pnum0)
(count-package package-bag17 city-loc-5 pnum0)
(count-package package-bag17 city-loc-6 pnum0)
(count-package package-bag17 city-loc-7 pnum0)
(count-package package-bag17 city-loc-8 pnum0)
(count-package package-bag17 city-loc-9 pnum0)
(count-package package-bag17 city-loc-10 pnum0)
(count-package package-bag17 city-loc-11 pnum0)
(count-package package-bag17 city-loc-12 pnum0)
(count-package package-bag17 city-loc-13 pnum0)
(count-package package-bag17 city-loc-14 pnum0)
(count-package package-bag17 city-loc-15 pnum0)
(count-package package-bag17 city-loc-16 pnum0)
(count-package package-bag17 city-loc-17 pnum0)
(count-package package-bag17 city-loc-18 pnum0)
(count-package package-bag17 city-loc-19 pnum0)
(count-package package-bag17 city-loc-20 pnum0)
(count-package package-bag17 city-loc-21 pnum0)
(count-package package-bag17 city-loc-22 pnum0)
(count-package package-bag17 city-loc-23 pnum0)
(count-package package-bag17 city-loc-24 pnum0)
(count-package package-bag17 city-loc-25 pnum0)
(count-package package-bag17 city-loc-26 pnum0)
(count-package package-bag17 city-loc-27 pnum0)
(count-package package-bag17 city-loc-28 pnum0)
(count-package package-bag17 city-loc-29 pnum0)
(count-package package-bag17 city-loc-30 pnum0)
(count-package package-bag17 city-loc-31 pnum0)
(count-package package-bag17 city-loc-32 pnum0)
(count-package package-bag17 city-loc-33 pnum0)
(count-package package-bag17 city-loc-34 pnum0)
(count-package package-bag17 city-loc-35 pnum0)
(count-package package-bag17 city-loc-36 pnum0)
(count-package package-bag17 city-loc-37 pnum0)
(count-package package-bag17 city-loc-38 pnum0)
(count-package package-bag17 city-loc-39 pnum0)
(count-package package-bag17 city-loc-40 pnum0)
(count-package package-bag17 city-loc-41 pnum0)
(count-package package-bag17 city-loc-42 pnum0)
(count-package package-bag17 city-loc-43 pnum0)
(count-package package-bag17 city-loc-44 pnum0)
(count-package package-bag17 city-loc-45 pnum0)
(count-package package-bag17 city-loc-46 pnum0)
(count-package package-bag17 city-loc-47 pnum0)
(count-package package-bag17 city-loc-48 pnum0)
(count-package package-bag17 city-loc-49 pnum0)
(count-package package-bag17 city-loc-50 pnum0)
(count-package package-bag17 city-loc-51 pnum0)
(count-package package-bag17 city-loc-53 pnum0)
(count-package package-bag17 city-loc-54 pnum0)
(count-package package-bag17 city-loc-55 pnum0)
(count-package package-bag17 city-loc-56 pnum0)
(count-package package-bag17 city-loc-57 pnum0)
(count-package package-bag17 city-loc-58 pnum0)
(count-package package-bag17 city-loc-59 pnum0)
(count-package package-bag17 city-loc-60 pnum0)
(count-package package-bag17 city-loc-61 pnum0)
(count-package package-bag17 city-loc-62 pnum0)
(count-package package-bag17 city-loc-63 pnum0)
(count-package package-bag18 truck-1 pnum0)
(count-package package-bag18 truck-2 pnum0)
(count-package package-bag18 truck-3 pnum0)
(count-package package-bag18 truck-4 pnum0)
(count-package package-bag18 city-loc-1 pnum0)
(count-package package-bag18 city-loc-2 pnum0)
(count-package package-bag18 city-loc-3 pnum0)
(count-package package-bag18 city-loc-4 pnum0)
(count-package package-bag18 city-loc-5 pnum0)
(count-package package-bag18 city-loc-6 pnum0)
(count-package package-bag18 city-loc-7 pnum0)
(count-package package-bag18 city-loc-8 pnum0)
(count-package package-bag18 city-loc-9 pnum0)
(count-package package-bag18 city-loc-10 pnum0)
(count-package package-bag18 city-loc-11 pnum0)
(count-package package-bag18 city-loc-12 pnum0)
(count-package package-bag18 city-loc-13 pnum0)
(count-package package-bag18 city-loc-14 pnum0)
(count-package package-bag18 city-loc-15 pnum0)
(count-package package-bag18 city-loc-16 pnum0)
(count-package package-bag18 city-loc-17 pnum0)
(count-package package-bag18 city-loc-18 pnum0)
(count-package package-bag18 city-loc-19 pnum0)
(count-package package-bag18 city-loc-20 pnum0)
(count-package package-bag18 city-loc-21 pnum0)
(count-package package-bag18 city-loc-22 pnum0)
(count-package package-bag18 city-loc-23 pnum0)
(count-package package-bag18 city-loc-24 pnum0)
(count-package package-bag18 city-loc-25 pnum0)
(count-package package-bag18 city-loc-26 pnum0)
(count-package package-bag18 city-loc-27 pnum0)
(count-package package-bag18 city-loc-28 pnum0)
(count-package package-bag18 city-loc-29 pnum0)
(count-package package-bag18 city-loc-30 pnum0)
(count-package package-bag18 city-loc-31 pnum0)
(count-package package-bag18 city-loc-32 pnum0)
(count-package package-bag18 city-loc-33 pnum0)
(count-package package-bag18 city-loc-34 pnum0)
(count-package package-bag18 city-loc-35 pnum0)
(count-package package-bag18 city-loc-36 pnum0)
(count-package package-bag18 city-loc-38 pnum0)
(count-package package-bag18 city-loc-39 pnum0)
(count-package package-bag18 city-loc-40 pnum0)
(count-package package-bag18 city-loc-41 pnum0)
(count-package package-bag18 city-loc-42 pnum0)
(count-package package-bag18 city-loc-43 pnum0)
(count-package package-bag18 city-loc-44 pnum0)
(count-package package-bag18 city-loc-45 pnum0)
(count-package package-bag18 city-loc-46 pnum0)
(count-package package-bag18 city-loc-47 pnum0)
(count-package package-bag18 city-loc-48 pnum0)
(count-package package-bag18 city-loc-49 pnum0)
(count-package package-bag18 city-loc-50 pnum0)
(count-package package-bag18 city-loc-51 pnum0)
(count-package package-bag18 city-loc-52 pnum0)
(count-package package-bag18 city-loc-53 pnum0)
(count-package package-bag18 city-loc-54 pnum0)
(count-package package-bag18 city-loc-55 pnum0)
(count-package package-bag18 city-loc-56 pnum0)
(count-package package-bag18 city-loc-57 pnum0)
(count-package package-bag18 city-loc-58 pnum0)
(count-package package-bag18 city-loc-59 pnum0)
(count-package package-bag18 city-loc-60 pnum0)
(count-package package-bag18 city-loc-61 pnum0)
(count-package package-bag18 city-loc-62 pnum0)
(count-package package-bag18 city-loc-63 pnum0)
(count-package package-bag19 truck-1 pnum0)
(count-package package-bag19 truck-2 pnum0)
(count-package package-bag19 truck-3 pnum0)
(count-package package-bag19 truck-4 pnum0)
(count-package package-bag19 city-loc-1 pnum0)
(count-package package-bag19 city-loc-2 pnum0)
(count-package package-bag19 city-loc-3 pnum0)
(count-package package-bag19 city-loc-4 pnum0)
(count-package package-bag19 city-loc-5 pnum0)
(count-package package-bag19 city-loc-6 pnum0)
(count-package package-bag19 city-loc-7 pnum0)
(count-package package-bag19 city-loc-8 pnum0)
(count-package package-bag19 city-loc-9 pnum0)
(count-package package-bag19 city-loc-10 pnum0)
(count-package package-bag19 city-loc-11 pnum0)
(count-package package-bag19 city-loc-12 pnum0)
(count-package package-bag19 city-loc-13 pnum0)
(count-package package-bag19 city-loc-14 pnum0)
(count-package package-bag19 city-loc-15 pnum0)
(count-package package-bag19 city-loc-16 pnum0)
(count-package package-bag19 city-loc-17 pnum0)
(count-package package-bag19 city-loc-18 pnum0)
(count-package package-bag19 city-loc-19 pnum0)
(count-package package-bag19 city-loc-20 pnum0)
(count-package package-bag19 city-loc-21 pnum0)
(count-package package-bag19 city-loc-22 pnum0)
(count-package package-bag19 city-loc-23 pnum0)
(count-package package-bag19 city-loc-24 pnum0)
(count-package package-bag19 city-loc-25 pnum0)
(count-package package-bag19 city-loc-26 pnum0)
(count-package package-bag19 city-loc-27 pnum0)
(count-package package-bag19 city-loc-28 pnum0)
(count-package package-bag19 city-loc-29 pnum0)
(count-package package-bag19 city-loc-30 pnum0)
(count-package package-bag19 city-loc-31 pnum0)
(count-package package-bag19 city-loc-32 pnum0)
(count-package package-bag19 city-loc-33 pnum0)
(count-package package-bag19 city-loc-34 pnum0)
(count-package package-bag19 city-loc-35 pnum0)
(count-package package-bag19 city-loc-36 pnum0)
(count-package package-bag19 city-loc-37 pnum0)
(count-package package-bag19 city-loc-38 pnum0)
(count-package package-bag19 city-loc-39 pnum0)
(count-package package-bag19 city-loc-40 pnum0)
(count-package package-bag19 city-loc-41 pnum0)
(count-package package-bag19 city-loc-42 pnum0)
(count-package package-bag19 city-loc-43 pnum0)
(count-package package-bag19 city-loc-44 pnum0)
(count-package package-bag19 city-loc-45 pnum0)
(count-package package-bag19 city-loc-46 pnum0)
(count-package package-bag19 city-loc-47 pnum0)
(count-package package-bag19 city-loc-48 pnum0)
(count-package package-bag19 city-loc-49 pnum0)
(count-package package-bag19 city-loc-50 pnum0)
(count-package package-bag19 city-loc-51 pnum0)
(count-package package-bag19 city-loc-52 pnum0)
(count-package package-bag19 city-loc-53 pnum0)
(count-package package-bag19 city-loc-54 pnum0)
(count-package package-bag19 city-loc-55 pnum0)
(count-package package-bag19 city-loc-56 pnum0)
(count-package package-bag19 city-loc-57 pnum0)
(count-package package-bag19 city-loc-58 pnum0)
(count-package package-bag19 city-loc-59 pnum0)
(count-package package-bag19 city-loc-61 pnum0)
(count-package package-bag19 city-loc-62 pnum0)
(count-package package-bag19 city-loc-63 pnum0)
(count-package package-bag20 truck-1 pnum0)
(count-package package-bag20 truck-2 pnum0)
(count-package package-bag20 truck-3 pnum0)
(count-package package-bag20 truck-4 pnum0)
(count-package package-bag20 city-loc-1 pnum0)
(count-package package-bag20 city-loc-2 pnum0)
(count-package package-bag20 city-loc-3 pnum0)
(count-package package-bag20 city-loc-4 pnum0)
(count-package package-bag20 city-loc-5 pnum0)
(count-package package-bag20 city-loc-6 pnum0)
(count-package package-bag20 city-loc-7 pnum0)
(count-package package-bag20 city-loc-8 pnum0)
(count-package package-bag20 city-loc-9 pnum0)
(count-package package-bag20 city-loc-10 pnum0)
(count-package package-bag20 city-loc-11 pnum0)
(count-package package-bag20 city-loc-12 pnum0)
(count-package package-bag20 city-loc-13 pnum0)
(count-package package-bag20 city-loc-14 pnum0)
(count-package package-bag20 city-loc-15 pnum0)
(count-package package-bag20 city-loc-16 pnum0)
(count-package package-bag20 city-loc-17 pnum0)
(count-package package-bag20 city-loc-18 pnum0)
(count-package package-bag20 city-loc-19 pnum0)
(count-package package-bag20 city-loc-20 pnum0)
(count-package package-bag20 city-loc-21 pnum0)
(count-package package-bag20 city-loc-22 pnum0)
(count-package package-bag20 city-loc-23 pnum0)
(count-package package-bag20 city-loc-24 pnum0)
(count-package package-bag20 city-loc-25 pnum0)
(count-package package-bag20 city-loc-26 pnum0)
(count-package package-bag20 city-loc-27 pnum0)
(count-package package-bag20 city-loc-28 pnum0)
(count-package package-bag20 city-loc-29 pnum0)
(count-package package-bag20 city-loc-30 pnum0)
(count-package package-bag20 city-loc-31 pnum0)
(count-package package-bag20 city-loc-32 pnum0)
(count-package package-bag20 city-loc-33 pnum0)
(count-package package-bag20 city-loc-34 pnum0)
(count-package package-bag20 city-loc-35 pnum0)
(count-package package-bag20 city-loc-36 pnum0)
(count-package package-bag20 city-loc-37 pnum0)
(count-package package-bag20 city-loc-38 pnum0)
(count-package package-bag20 city-loc-39 pnum0)
(count-package package-bag20 city-loc-40 pnum0)
(count-package package-bag20 city-loc-41 pnum0)
(count-package package-bag20 city-loc-42 pnum0)
(count-package package-bag20 city-loc-43 pnum0)
(count-package package-bag20 city-loc-45 pnum0)
(count-package package-bag20 city-loc-46 pnum0)
(count-package package-bag20 city-loc-47 pnum0)
(count-package package-bag20 city-loc-48 pnum0)
(count-package package-bag20 city-loc-49 pnum0)
(count-package package-bag20 city-loc-50 pnum0)
(count-package package-bag20 city-loc-51 pnum0)
(count-package package-bag20 city-loc-52 pnum0)
(count-package package-bag20 city-loc-53 pnum0)
(count-package package-bag20 city-loc-54 pnum0)
(count-package package-bag20 city-loc-55 pnum0)
(count-package package-bag20 city-loc-56 pnum0)
(count-package package-bag20 city-loc-57 pnum0)
(count-package package-bag20 city-loc-58 pnum0)
(count-package package-bag20 city-loc-59 pnum0)
(count-package package-bag20 city-loc-60 pnum0)
(count-package package-bag20 city-loc-61 pnum0)
(count-package package-bag20 city-loc-62 pnum0)
(count-package package-bag20 city-loc-63 pnum0)
(count-package package-bag21 truck-1 pnum0)
(count-package package-bag21 truck-2 pnum0)
(count-package package-bag21 truck-3 pnum0)
(count-package package-bag21 truck-4 pnum0)
(count-package package-bag21 city-loc-1 pnum0)
(count-package package-bag21 city-loc-2 pnum0)
(count-package package-bag21 city-loc-3 pnum0)
(count-package package-bag21 city-loc-4 pnum0)
(count-package package-bag21 city-loc-5 pnum0)
(count-package package-bag21 city-loc-7 pnum0)
(count-package package-bag21 city-loc-8 pnum0)
(count-package package-bag21 city-loc-9 pnum0)
(count-package package-bag21 city-loc-10 pnum0)
(count-package package-bag21 city-loc-11 pnum0)
(count-package package-bag21 city-loc-12 pnum0)
(count-package package-bag21 city-loc-13 pnum0)
(count-package package-bag21 city-loc-14 pnum0)
(count-package package-bag21 city-loc-15 pnum0)
(count-package package-bag21 city-loc-16 pnum0)
(count-package package-bag21 city-loc-17 pnum0)
(count-package package-bag21 city-loc-18 pnum0)
(count-package package-bag21 city-loc-19 pnum0)
(count-package package-bag21 city-loc-20 pnum0)
(count-package package-bag21 city-loc-21 pnum0)
(count-package package-bag21 city-loc-22 pnum0)
(count-package package-bag21 city-loc-23 pnum0)
(count-package package-bag21 city-loc-24 pnum0)
(count-package package-bag21 city-loc-25 pnum0)
(count-package package-bag21 city-loc-26 pnum0)
(count-package package-bag21 city-loc-27 pnum0)
(count-package package-bag21 city-loc-28 pnum0)
(count-package package-bag21 city-loc-29 pnum0)
(count-package package-bag21 city-loc-30 pnum0)
(count-package package-bag21 city-loc-31 pnum0)
(count-package package-bag21 city-loc-32 pnum0)
(count-package package-bag21 city-loc-33 pnum0)
(count-package package-bag21 city-loc-34 pnum0)
(count-package package-bag21 city-loc-35 pnum0)
(count-package package-bag21 city-loc-36 pnum0)
(count-package package-bag21 city-loc-37 pnum0)
(count-package package-bag21 city-loc-38 pnum0)
(count-package package-bag21 city-loc-39 pnum0)
(count-package package-bag21 city-loc-40 pnum0)
(count-package package-bag21 city-loc-41 pnum0)
(count-package package-bag21 city-loc-42 pnum0)
(count-package package-bag21 city-loc-43 pnum0)
(count-package package-bag21 city-loc-44 pnum0)
(count-package package-bag21 city-loc-45 pnum0)
(count-package package-bag21 city-loc-46 pnum0)
(count-package package-bag21 city-loc-47 pnum0)
(count-package package-bag21 city-loc-48 pnum0)
(count-package package-bag21 city-loc-49 pnum0)
(count-package package-bag21 city-loc-50 pnum0)
(count-package package-bag21 city-loc-51 pnum0)
(count-package package-bag21 city-loc-52 pnum0)
(count-package package-bag21 city-loc-53 pnum0)
(count-package package-bag21 city-loc-54 pnum0)
(count-package package-bag21 city-loc-55 pnum0)
(count-package package-bag21 city-loc-56 pnum0)
(count-package package-bag21 city-loc-57 pnum0)
(count-package package-bag21 city-loc-58 pnum0)
(count-package package-bag21 city-loc-59 pnum0)
(count-package package-bag21 city-loc-60 pnum0)
(count-package package-bag21 city-loc-61 pnum0)
(count-package package-bag21 city-loc-62 pnum0)
(count-package package-bag21 city-loc-63 pnum0)
(count-package package-bag22 truck-1 pnum0)
(count-package package-bag22 truck-2 pnum0)
(count-package package-bag22 truck-3 pnum0)
(count-package package-bag22 truck-4 pnum0)
(count-package package-bag22 city-loc-1 pnum0)
(count-package package-bag22 city-loc-2 pnum0)
(count-package package-bag22 city-loc-3 pnum0)
(count-package package-bag22 city-loc-4 pnum0)
(count-package package-bag22 city-loc-5 pnum0)
(count-package package-bag22 city-loc-6 pnum0)
(count-package package-bag22 city-loc-7 pnum0)
(count-package package-bag22 city-loc-8 pnum0)
(count-package package-bag22 city-loc-9 pnum0)
(count-package package-bag22 city-loc-10 pnum0)
(count-package package-bag22 city-loc-11 pnum0)
(count-package package-bag22 city-loc-12 pnum0)
(count-package package-bag22 city-loc-13 pnum0)
(count-package package-bag22 city-loc-14 pnum0)
(count-package package-bag22 city-loc-15 pnum0)
(count-package package-bag22 city-loc-16 pnum0)
(count-package package-bag22 city-loc-17 pnum0)
(count-package package-bag22 city-loc-19 pnum0)
(count-package package-bag22 city-loc-20 pnum0)
(count-package package-bag22 city-loc-21 pnum0)
(count-package package-bag22 city-loc-22 pnum0)
(count-package package-bag22 city-loc-23 pnum0)
(count-package package-bag22 city-loc-24 pnum0)
(count-package package-bag22 city-loc-25 pnum0)
(count-package package-bag22 city-loc-26 pnum0)
(count-package package-bag22 city-loc-27 pnum0)
(count-package package-bag22 city-loc-28 pnum0)
(count-package package-bag22 city-loc-29 pnum0)
(count-package package-bag22 city-loc-30 pnum0)
(count-package package-bag22 city-loc-31 pnum0)
(count-package package-bag22 city-loc-32 pnum0)
(count-package package-bag22 city-loc-33 pnum0)
(count-package package-bag22 city-loc-34 pnum0)
(count-package package-bag22 city-loc-35 pnum0)
(count-package package-bag22 city-loc-36 pnum0)
(count-package package-bag22 city-loc-37 pnum0)
(count-package package-bag22 city-loc-38 pnum0)
(count-package package-bag22 city-loc-39 pnum0)
(count-package package-bag22 city-loc-40 pnum0)
(count-package package-bag22 city-loc-41 pnum0)
(count-package package-bag22 city-loc-42 pnum0)
(count-package package-bag22 city-loc-43 pnum0)
(count-package package-bag22 city-loc-44 pnum0)
(count-package package-bag22 city-loc-45 pnum0)
(count-package package-bag22 city-loc-46 pnum0)
(count-package package-bag22 city-loc-47 pnum0)
(count-package package-bag22 city-loc-48 pnum0)
(count-package package-bag22 city-loc-49 pnum0)
(count-package package-bag22 city-loc-50 pnum0)
(count-package package-bag22 city-loc-51 pnum0)
(count-package package-bag22 city-loc-52 pnum0)
(count-package package-bag22 city-loc-53 pnum0)
(count-package package-bag22 city-loc-54 pnum0)
(count-package package-bag22 city-loc-55 pnum0)
(count-package package-bag22 city-loc-56 pnum0)
(count-package package-bag22 city-loc-57 pnum0)
(count-package package-bag22 city-loc-58 pnum0)
(count-package package-bag22 city-loc-59 pnum0)
(count-package package-bag22 city-loc-60 pnum0)
(count-package package-bag22 city-loc-61 pnum0)
(count-package package-bag22 city-loc-62 pnum0)
(count-package package-bag22 city-loc-63 pnum0)
(package-bag-size package-bag1 pnum3)
(package-bag-size package-bag2 pnum2)
(package-bag-size package-bag3 pnum2)
(package-bag-size package-bag4 pnum2)
(package-bag-size package-bag5 pnum2)
(package-bag-size package-bag6 pnum2)
(package-bag-size package-bag7 pnum2)
(package-bag-size package-bag8 pnum1)
(package-bag-size package-bag9 pnum1)
(package-bag-size package-bag10 pnum1)
(package-bag-size package-bag11 pnum1)
(package-bag-size package-bag12 pnum1)
(package-bag-size package-bag13 pnum1)
(package-bag-size package-bag14 pnum1)
(package-bag-size package-bag15 pnum1)
(package-bag-size package-bag16 pnum1)
(package-bag-size package-bag17 pnum1)
(package-bag-size package-bag18 pnum1)
(package-bag-size package-bag19 pnum1)
(package-bag-size package-bag20 pnum1)
(package-bag-size package-bag21 pnum1)
(package-bag-size package-bag22 pnum1)
(package-lte-sum pnum0 pnum0 pnum3)
(package-lte-sum pnum0 pnum1 pnum3)
(package-lte-sum pnum0 pnum2 pnum3)
(package-lte-sum pnum0 pnum3 pnum3)
(package-lte-sum pnum1 pnum0 pnum3)
(package-lte-sum pnum1 pnum1 pnum3)
(package-lte-sum pnum1 pnum2 pnum3)
(package-lte-sum pnum2 pnum0 pnum3)
(package-lte-sum pnum2 pnum1 pnum3)
(package-lte-sum pnum3 pnum0 pnum3)
(package-lte-sum pnum0 pnum0 pnum2)
(package-lte-sum pnum0 pnum1 pnum2)
(package-lte-sum pnum0 pnum2 pnum2)
(package-lte-sum pnum1 pnum0 pnum2)
(package-lte-sum pnum1 pnum1 pnum2)
(package-lte-sum pnum2 pnum0 pnum2)
(package-lte-sum pnum0 pnum0 pnum1)
(package-lte-sum pnum0 pnum1 pnum1)
(package-lte-sum pnum1 pnum0 pnum1)
)
(:goal (and
	  (count-package package-bag1 city-loc-29 pnum1)
	  (count-package package-bag1 city-loc-37 pnum1)
	  (count-package package-bag1 city-loc-7 pnum1)
	  (count-package package-bag2 city-loc-9 pnum2)
	  (count-package package-bag3 city-loc-19 pnum2)
	  (count-package package-bag4 city-loc-4 pnum2)
	  (count-package package-bag5 city-loc-17 pnum2)
	  (count-package package-bag6 city-loc-8 pnum2)
	  (count-package package-bag7 city-loc-53 pnum1)
	  (count-package package-bag7 city-loc-42 pnum1)
	  (count-package package-bag8 city-loc-28 pnum1)
	  (count-package package-bag9 city-loc-1 pnum1)
	  (count-package package-bag10 city-loc-43 pnum1)
	  (count-package package-bag11 city-loc-39 pnum1)
	  (count-package package-bag12 city-loc-29 pnum1)
	  (count-package package-bag13 city-loc-21 pnum1)
	  (count-package package-bag14 city-loc-11 pnum1)
	  (count-package package-bag15 city-loc-25 pnum1)
	  (count-package package-bag16 city-loc-46 pnum1)
	  (count-package package-bag17 city-loc-31 pnum1)
	  (count-package package-bag18 city-loc-50 pnum1)
	  (count-package package-bag19 city-loc-5 pnum1)
	  (count-package package-bag20 city-loc-45 pnum1)
	  (count-package package-bag21 city-loc-18 pnum1)
	  (count-package package-bag22 city-loc-61 pnum1))
)
(:metric minimize (total-cost))
)
